### PR TITLE
Dark theme

### PR DESCRIPTION
**Pull request by maxgrapps**
Design
design

### CODE REVIEW

**Comment by maxgrapps** [comment]
@vbaranov Can you help me with gettext error, please? I executed mix gettext.extract —merge in the root and apps/block_scout_web folders. Why it's still not working?

**Comment by vbaranov** [comment]
@maxgrapps 

>I executed mix gettext.extract —merge in the root

this is wrong. You should do it only from the Umbrella project's root, not from the root folder of the whole application.

Please, take a look:
https://poanetwork.github.io/blockscout/#/internationalization?id=internationalization

**Comment by maxgrapps** [comment]
@vbaranov Yes, I executed it, but it still failed. Why it can be?

**Comment by vbaranov** [comment]
@maxgrapps did you try to set unchanged both internalization files (from poanetwork/dark-theme) and follow the instruction above? It should help. the problem is that probably you contaminated internalization files by executing merging command from the root folder

**Comment by maxgrapps** [comment]
@vbaranov I copied code from original repo for:
apps/block_scout_web/priv/gettext/default.pot
apps/block_scout_web/priv/gettext/errors.pot
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
apps/block_scout_web/priv/gettext/en/LC_MESSAGES/errors.po
and executed cd apps/block_scout_web; mix gettext.extract --merge; cd -
Is it correct?

**Pull request merged**
