### PR TITLE
Re-implement Geth JS internal transaction tracer in Elixir

### LINKED ISSUE #1607: JSON RPC Endpoint Variant
No Endpoint Variant available for aleth (formerly cpp-ethereum).

Need to add RPC endpoint variant configuration for aleth.

### PR DESCRIPTION
**Pull request by goodsoft**
Resolves #1607 

## Motivation

Currently in Geth variant raw opcode traces are converted into internal_transactions using a custom JS tracer in `priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js`. cpp-ethereum nodes don't support custom JS tracers and return raw traces regardless of provided parameters.

## Changes

This PR adds an Elixir implementation of the tracer, which is utilized in case raw traces are detected in the response from the node. It was cross-checked for correctness with Geth built-in [`callTracer`](https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/internal/tracers/call_tracer.js
). In the process some bugs were discovered in our JS tracer, which will be fixed with a separate PR.

Unlike JS tracer we don't have access to EVM internal state during tracing, so additional requests to node are performed: transactions and receipts are fetched before tracing, created contract codes and pre-selfdestruct balances are fetched after.

## Checklist for your PR

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so if necessary

### CODE REVIEW

**Comment by goodsoft** [comment]
Automated testing is rather hard in the absence of live Geth node, as we can't cross-check it with JS tracer. Also, raw traces are too huge to be included verbatim.

I'll try to cut out relevant parts of traces, though.

**Comment by goodsoft** [comment]
This looks totally unrelated to internal transaction tracing, but rather to `BLOCK_TRANSFORMER` env variable, which should or should not be `clique`.

Also, this PR shouldn't really have any effect on any deployed instances, because the tracer is only ised in case the node doesn't support JS tracer (e.g. cpp-ethereum).

**Comment by vbaranov** [comment]
Yes, and regarding your comment 
>Also, this PR shouldn't really have any effect on any deployed instances, because the tracer is only ised in case the node doesn't support JS tracer (e.g. cpp-ethereum).

It apriori shouldn't break something for Rinkeby 😄

**Comment by karalabe** [comment]
Saw this PR just now. Quick question, do you now transfer a full opcode trace from Geth to BlockScount and analyze it afterward? Because if so, that's going to blow with a big transaction, since the data transfer + JSON encoding is huge. I'd also think it's a lot slower, isn't it?

**Comment by goodsoft** [comment]
No, this code is only a fallback for Geth-compatible nodes that don't support JS tracers, e.g. cpp-ethereum.
They would send _the entire opcode trace_ regardless of supplied params, so no way to optimize the payload there anyway.

**Comment by karalabe** [comment]
Thx!

**Pull request merged**
