### PR TITLE
#1299 Make coinmarketcap informations optional

### PR DESCRIPTION
**Pull request by SurfingNerd**
made it possible to make coinmarketcap informations invisible.
how to: add this import in app.scss in your branch:

@import "components/deactivate_coinmarket";

Details: See Issue #1299

### CODE REVIEW

**Comment by zachdaniel** [comment]
A part of me would like to see this in the application configuration, as there are probably other optimizations that could be made for a chain an explorer that doesn't care about market cap (like we could avoid calculating it and publishing it to the client at all). However, this does exactly what it says it does, and I see no reason not to go with it, and optimize the backend w/ that setting later if it becomes necessary.

**Comment by zachdaniel** [comment]
A part of me would like to see this in the application configuration, as there are probably other optimizations that could be made for a chain an explorer that doesn't care about market cap (like we could avoid calculating it and publishing it to the client at all). However, this does exactly what it says it does, and I see no reason not to go with it, and optimize the backend w/ that setting later if it becomes necessary.

**Comment by SurfingNerd** [comment]
Does this PR solve the same Issue: https://github.com/poanetwork/blockscout/pull/1492 ? 
then i should close this pull request and switch to official Solution once next update ??

**Comment by zachdaniel** [comment]
@ayrat555 could you double check that your PR covers this use case? If so, we can close this PR.

**Comment by ayrat555** [comment]
it's the same as #1492

**Pull request closed without merging**
