### PR TITLE
Fix issues in Staking Dapp related to pool filters

### PR DESCRIPTION
**Pull request by liberumed**
## Motivation
Some remain issues related to pool filters
https://github.com/poanetwork/blockscout/pull/2292#issuecomment-531745134

About 16.09.2019-3. "should be animation on items disappearing on Inactive pools table?"
- I can't reproduce an issue or not sure what part we talk about or @vbaranov 

## Changelog
  - [x] Fix disappearing pagination on pools filter toggle (16.09.2019-2)
  - [x] Wrap stakes table items in container to set minimum heigh (16.09.2019-1)

### CODE REVIEW

**Comment by liberumed** [comment]
@vbaranov Are you have any suggestions on how to solve "Did not solved. I still see flickering on filter applying or just without filter, when just open Inactive pools tab" ?
In my case, I see some animation of disappearing/appearing of items in the list and footer part is moving up/down in case of toggling a filter, so I set some minimum heigh for items container to reduce this effect. But not sure how to completely get rid of it. Can set a min height of block = to heigh of the block with an error message, but in this case, the heigh can be too big for the list with one element.

**Comment by vbaranov** [comment]
@liberumed 
>Are you have any suggestions on how to solve

Screenshot 2019-09-25 at 19 29 27

Let's decrease bottom padding of *plus* page to make it equal the top one 

and 👇 

>Can set a min height of block = to heigh of the block with an error message

Does it sound good?

**Comment by liberumed** [comment]
So 16.09.2019-1. Flickering on the filter applied should be fixed now. 
But having problem to fix 16.09.2019-3. should be animation on items disappearing on Inactive pools table? - Disappearing can be easily turned on but it switched off intentionally because appearing of Empty Container happening in the same time with the disappearing of items so it looks more ugly than just instance disappearing/appearing. And had a hard time trying to fix it but without any big success to put them in a chaing or adding various delays in disappearing/appearing. Fixing it will take more time and don't see it as major issue for now. So waiting for your instructions @vbaranov 
Animation of disappearing of items in list happening here: 
apps/block_scout_web/assets/js/lib/list_morph.js :38
```
  let canAnimate = !horizontal && newList.length > 0
```

This one is responsible for appearing of Empty Items section
apps/block_scout_web/assets/js/lib/async_listing_load.js :147
```
'[data-async-listing] [data-empty-response-message]': {
    render ($el, state) {
      if (
        !state.requestError &&
        (!state.loading) &&
        state.items.length === 0
      ) {
        return $el.show()
      }

      $el.hide()
    }
  },
```

**Comment by vbaranov** [comment]
@liberumed let's leave `16.09.2019-3` as is for now. Other bugs solved.

**Pull request merged**
