### PR TITLE
get rid of cldr warnings

### PR DESCRIPTION
**Pull request by ayrat555**
During compilation, cldr generates a lot of warnings
```
warning: passing float to Decimal.new/1 is deprecated, use Decimal.from_float/1 instead
  (decimal) lib/decimal.ex:1063: Decimal.new/1
  (ex_cldr) lib/cldr/helpers/math.ex:606: Cldr.Math.sqrt/2
  (ex_cldr) lib/cldr/helpers/math.ex:309: Cldr.Math.log/1
  (ex_cldr) lib/cldr/helpers/math.ex:360: Cldr.Math.log10/1
  (ex_cldr) lib/cldr/helpers/math.ex:261: Cldr.Math.round_significant/2
  (ex_cldr_numbers) lib/number/formatter/decimal_formatter.ex:203: Cldr.Number.Formatter.Decimal.set_exponent/3
  (ex_cldr_numbers) lib/number/formatter/decimal_formatter.ex:91: Cldr.Number.Formatter.Decimal.do_to_string/3
  (ex_cldr_numbers) lib/number.ex:275: Cldr.Number.to_string/2
  (ex_cldr_numbers) lib/number.ex:310: Cldr.Number.to_string!/2
  (block_scout_web) lib/block_scout_web/views/wei_helpers.ex:63: BlockScoutWeb.WeiHelpers.format_wei_value/3
  (block_scout_web) lib/block_scout_web/views/transaction_view.ex:257: BlockScoutWeb.TransactionView.fee_to_denomination/2
  (block_scout_web) lib/block_scout_web/views/transaction_view.ex:129: BlockScoutWeb.TransactionView.formatted_fee/2
  (block_scout_web) lib/block_scout_web/templates/transaction/_tile.html.eex:33: BlockScoutWeb.TransactionView."_tile.html"/1
  (phoenix) lib/phoenix/view.ex:399: Phoenix.View.render_to_iodata/3
  (phoenix) lib/phoenix/view.ex:406: Phoenix.View.render_to_string/3
  (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
  (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
```
for example https://circleci.com/gh/poanetwork/blockscout/130565?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

## Changelog

- get rid of cldr warnings

### CODE REVIEW

**Comment by kipcole9** [comment]
I recommend:
```elixir
mix deps.update cldr_utils
```
You should then be on [version 2.3.0](https://github.com/elixir-cldr/cldr_utils/releases/tag/v2.3.0) which does not have this issue.  In fact the issue was fixed [in this commit](https://github.com/elixir-cldr/cldr_utils/commit/e14d27160f0f37de551d1009fff7f7be769a4c4e) and as on `cldr_utils` version 2.0.2.

**Comment by ayrat555** [comment]
@kipcole9 `cldr_utils` is updated to `2.3.0` in this PR. https://github.com/poanetwork/blockscout/pull/2473/files#diff-7234367b857fd47fe1b5d1bcfd7e05edR18

If I update only `cldr_utils` compilation is failing

**Comment by Schultzer** [comment]
I would try not to cache the `_build` directory in your circle ci config.

**Comment by kipcole9** [comment]
@Schultzer Good point.  During the generation of a Cldr module, a number of subsidiary modules are created and I don't know of a way to avoid overwriting any pre-existing module of the same name.  However if its also happening on your dev machine, as you indicated, then thats a different cause which I'll look into.

**Pull request merged**
