### PR TITLE
Transaction history

### LINKED ISSUE #811: Add the option for Transactions per day graph on the homepage
Not all networks will have a coin that has a USD value or may just be a testnet or private network. In these cases the homepage graph does not make sense. Instead of the USD chart we should provide a graph showing transactions per minute. All networks will be able to show this. A configurable option in `block_scout_web` would be convenient as well :+1: 

In this same issue, we should also remove the requirement to define a coin in `apps/explorer/config/config.exs`

### PR DESCRIPTION
**Pull request by kuberlog**
fixes #811 

see PR #2404

### CODE REVIEW

**Comment by vbaranov** [comment]
@SlightlyCyborg 

I exported 
```
ENABLE_TXS_STATS=true
SHOW_TXS_CHART=true
```

But don't see txs chart:
Screenshot 2019-08-01 at 18 54 16

What is missing? I built from `staging-mainnet-stg` branch where merged your PR

**Comment by vbaranov** [comment]
The same issue if I started from the current branch

**Comment by SlightlyCyborg** [comment]
sorry. I used SHOW_TX_CHART instead to SHOW_TXS_CHART. I just pushed up a change Try it now with SHOW_TXS_CHART

**Comment by vbaranov** [comment]
@SlightlyCyborg I left your update for a weekend on our stg server (ETH Mainnet chain) and after 2 days I see: 
Screenshot 2019-08-04 at 21 03 27

I used the same set of ENV vars, that I posted in the previous post.

**Comment by SlightlyCyborg** [comment]
IDK. It is hard to tell what is going on without having access to that server.

**Comment by vbaranov** [comment]
@SlightlyCyborg

I think the problem is with that
>by joining blocks table with transactions table and then counting them

Our stg server is for ETH Mainnet chain where >500 millions of transactions and >8 millions of blocks. Is it possible to skip this initial setup of getting a history of transactions if this can not be getting done for such huge tables?

And the 2nd question, but no less important, is why hourly update doesn't work? Did you try this solution on some public chains?

**Comment by SlightlyCyborg** [comment]
If the 365 day init throws an exception than the hourly will never run, because it is tied to the same process, which will always throw an exception. 

No. I did not use any public chains. i tried and then realized I didn't have good enough hardware. I am developing on a MacBook Air. Any suggestions?

**Comment by vbaranov** [comment]
>If the 365 day init throws an exception than the hourly will never run, because it is tied to the same process, which will always throw an exception.

Will decreasing of an initial period make the initial bootstrap more stable? If yes, I'd suggest making at least the initial period configurable otherwise most likely it will not work on real chains as we see for ETH Mainnet.

>No. I did not use any public chains. i tried and then realized I didn't have good enough hardware. I am developing on a MacBook Air. Any suggestions?

Goerli chain as one of the smallest to help. I believe it could be synced on a laptop.

**Comment by SlightlyCyborg** [comment]
> Will decreasing of an initial period make the initial bootstrap more stable?

No. I think if it can handle 1 day, then it can handle 365. At init, it makes 365 separate DB count queries, 1 for each day. It only moves on to the next day after the DB has counted all the transactions for the previous day in the requested batch. https://github.com/poanetwork/blockscout/pull/2480/files#diff-0e35d7b780b58d157db92884d81295acR25

Do you see the HistorianProcess restarting in the error logs? Can you give me the logs?

**Comment by SlightlyCyborg** [comment]
Anyway, ya, I can make the num of days configurable. Also I am going to set a configurable lag between when the app starts til when the Historian compiles its initial data, in order to let the indexer finish inserting the relevant data into the DB.

**Comment by vbaranov** [comment]
>Do you see the HistorianProcess restarting in the error logs? Can you give me the logs?

The information from logs keeps in an hour on stg. Absolutely nothing related to historian process in the error logs for that hour.

>Also, just double checking... you are doing an ecto.migrate in a docker instance or something? I added a new table.

Yes. `transaction_stats` table has been created on stg server and it is empty for 4 days. And please see my previous comment: you need to put table creation into migrations for the sake of consistency.

**Comment by vbaranov** [comment]
@SlightlyCyborg 

*Update*:
After several restarts of the application initial data appeared. At the same time, it doesn't cancel all proposals, made before in order to make bootstrap stronger. It would be awesome if you will implement them.

Screenshot 2019-08-06 at 13 23 25

One more issue: values of the chart tickers on the right are cut

**Comment by SlightlyCyborg** [comment]
Ok. Changes incoming in a few hours.

**Comment by SlightlyCyborg** [comment]
@vbaranov, hope you are having a good day so far.

In blockscout_web, I fixed the legend color, the legend padding problem, and the right axis cutoff. Also I realized I wasn't updating the legend when new data came in, so I fixed that as well.

In explorer, I added 2 ENV vars: 
1. TXS_HISTORIAN_INIT_LAG, which tells the historian to not compile the initial days of txs stats until x number of minutes have passed. This allows the indexer to save all the txs to the database before the historian counts them.
2. TXS_STATS_DAYS_TO_COMPILE_AT_INIT, which tells the historian how many days to compile at init. The default is 40.

I already added the `transaction_stats` table to migrations in a commit.

Hopefully this takes care of everything on my end.

**Comment by vbaranov** [comment]
@SlightlyCyborg the update looks great. Gonna test it today

**Comment by vbaranov** [comment]
@SlightlyCyborg I had to update *transactions-history* branch with updates from master branch because of broken `absinthe` dependency:
```
* Updating absinthe_phoenix (https://github.com/ayrat555/absinthe_phoenix.git)
fatal: reference is not a tree: 4104c7213c328c3698b52710d49cd6d85449305c
** (Mix) Command "git --git-dir=.git checkout --quiet 4104c7213c328c3698b52710d49cd6d85449305c" failed
```

your branch fails on compilation due to this error too. Could you please get updates from upstream and resolve merging conflicts?

**Comment by vbaranov** [comment]
@SlightlyCyborg I asked you to try resolve merging conflicts because when I try to do that, I get
```
== Compilation error in file lib/block_scout_web/controllers/chain_controller.ex ==
** (CompileError) lib/block_scout_web/controllers/chain_controller.ex:33: undefined function transaction_history_chart_path/2
    (elixir) src/elixir_locals.erl:108: :elixir_locals."-ensure_no_undefined_local/3-lc$^0/1-0-"/2
    (elixir) src/elixir_locals.erl:109: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
could not compile dependency :block_scout_web, "mix compile" failed. You can recompile this dependency with "mix deps.compile block_scout_web", update it with "mix deps.update block_scout_web" or clean it with "mix deps.clean block_scout_web"
```

on a compilation and have no idea how to fix. I believe you have more insights on *transaction_history_chart_path* function since you introduced it in your PR. Waiting for your reply before update our staging application with this feature.

**Comment by SlightlyCyborg** [comment]
@vbaranov, sure

I was getting some sleep. I'll do it right now. That problem is pretty easy to solve.

**Comment by vbaranov** [comment]
@SlightlyCyborg thanks, could you please fix credo, dialyzer, gettext. Credo and gettext should be easy. Not sure what with Dialyzer test.

**Comment by SlightlyCyborg** [comment]
Ok. I'm waiting on the dialyzer to generate the plt. I will push soon.

**Comment by SlightlyCyborg** [comment]
@vbaranov, dialyzer is taking a long time on my machine, so I used CI to diagnose and fix the error and I am pushing up blind. It may fail dialyzer, but I think I fixed the problem.

**Comment by SlightlyCyborg** [comment]
@vbaranov ok, I don't know how to fix the gettext error. Any help?

**Comment by SlightlyCyborg** [comment]
Everything looks ok: @vbaranov.

**Comment by vbaranov** [comment]
@SlightlyCyborg I tested the update. It looks great! One issue I found: if I hide price chart, tickers are cut at the left axis

Screenshot 2019-08-15 at 23 14 52

**Comment by SlightlyCyborg** [comment]
@vbaranov ok. I just added some padding on the left hand side like I did on the right.

**Comment by SlightlyCyborg** [comment]
@vbaranov, do you plan on getting to this today?

**Comment by vbaranov** [comment]
@SlightlyCyborg I left this feature for the 24 hours on stg server and today I don't see new records:

Screenshot 2019-08-16 at 15 04 53

Do you have an idea why it could be?

**Comment by SlightlyCyborg** [comment]
Are relevant ENV vars set?

Here is the relevant section of my setup:

`export SHOW_TXS_CHART=true
export SHOW_PRICE_CHART=false
export HISTORY_FETCH_INTERVAL=60
export ENABLE_TXS_STATS=true
export TXS_HISTORIAN_INIT_LAG=5
export TXS_STATS_DAYS_TO_COMPILE_AT_INIT=10
`

**Comment by SlightlyCyborg** [comment]
Other than that, I will probe around the code later today to sus out the problem.

**Comment by vbaranov** [comment]
@SlightlyCyborg 
I used
```
ENABLE_TXS_STATS=true
SHOW_TXS_CHART=true
```
because AFAIU the other params have default values. Meanwhile, I will try your set.

**Comment by vbaranov** [comment]
@SlightlyCyborg the same with your set of parameters: `Tx/day 0` for the last 2 days.

**Comment by SlightlyCyborg** [comment]
@vbaranov Ok. I'll look into it.

**Comment by vbaranov** [comment]
@SlightlyCyborg still *zeros* during this week btw. Despite we recreated our staging server several times during the week.

**Comment by vbaranov** [comment]
@kuberlog I was managed to finalize your PR. I created a new one https://github.com/poanetwork/blockscout/pull/3065 based on the changes you made. The issue of why the stats were stopping to gather was because of the performance of the query to get the transactions counter. It was not optimized for transactions table of hundreds of thousands/millions of transactions. I fixed the performance of that query in this commit https://github.com/poanetwork/blockscout/pull/3065/commits/9311a3b56618bf6b03560cd6bfbbfc0fb998b1ae. Anyways, thanks for your contribution. You made most of the logic to cover the opened bounty.

**Pull request merged**
