### PR TITLE
use only one query instead of two for blocks on main page

### PR DESCRIPTION
**Pull request by ayrat555**
part of https://github.com/poanetwork/blockscout/issues/1880

## Changelog

- use only one query instead of two for blocks on main page

### CODE REVIEW

**Comment by ayrat555** [comment]
@vbaranov after comparing it was found that counting transactions in the query is actually slower. I think it's because the transaction table is very large. 

so this PR fixes another issue.
Currently, we're using two queries to load blocks:
1. Query to fetch blocks
2. Query to preload association (transactions etc)

This PR now uses only one transaction.

**Comment by vbaranov** [comment]
@ayrat555 did you find any proofs that the combined query will work faster?

**Comment by vbaranov** [comment]
@ayrat555 should we close it without merging?

**Comment by vbaranov** [comment]
As agreed we can close it

**Pull request closed without merging**
