### PR TITLE
Changes to #2637 PR : Internationalization added;  ERC721 image removed from Token Transfers page.

### PR DESCRIPTION
**Pull request by YegorSan**
This PR is related to the changes requested in #2637 PR.

## Motivation
Internationalization was required.
ERC 721 image must be removed from token transfer page.

### Enhancements
* As ERC721 token instance must be a new separate page , I've removed container with the ERC 721 image from token transfer page.
* Added internationalization in order to fix _gettext_ issue as requested.

## Checklist for your PR

  - [ ] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so if necessary
  - [ ] If I added/changed/removed ENV var, I should update the list of env vars in https://github.com/poanetwork/blockscout/blob/master/docs/env-variables.md to reflect changes in the table here https://poanetwork.github.io/blockscout/#/env-variables?id=blockscout-env-variables. I've set `master` in the `Version` column.
  - [ ] If I add new indices into DB, I checked, that they don't redundant with PGHero or other tools

### CODE REVIEW

**Comment by YegorSan** [comment]
I've added internationalization using https://poanetwork.github.io/blockscout/#/internationalization?id=internationalization guide. The following command was executed straightly from main blockscout folder :  

**cd apps/block_scout_web; mix gettext.extract --merge; cd -**

 For some reason as I can see tests failed on CircleCI for gettext.

**Comment by ayrat555** [comment]
@YegorSan hi. Can you please explain why are you creating so many PR related to the same changes?

**Comment by ayrat555** [comment]
please you the previous PR

**Comment by YegorSan** [comment]
@ayrat555  hi. I've had a call with Victor yesterday, and as far as I understand - for each new update  new branch must be added to my forked repo, and then I must create new PR to front-update branch from already created branch in my forked repo with the updates. That's why I've created a new branch related to the #2637 PR with the performed changes. If I am doing wrong, sorry for misunderstanding. If yes - please provide some information which way to use to update the PR. This question is not clear for me, and it would be great to prevent such a mistakes in future. Thank you.

**Comment by vbaranov** [comment]
@YegorSan this PR contains changes from #2637. It shouldn't be done this way. Each PR should consist of changes specific to the problem you are trying to solve. And please resolve issues with that PR https://github.com/poanetwork/blockscout/pull/2637#pullrequestreview-280298261. Let's focus on it do deliver it correctly.

**Comment by YegorSan** [comment]
@vbaranov 
Ok. I am sorry for misunderstanding. I will push the changes to the local branch frontend-tasks which was created for #2637 PR issues.  Please let me know, why the test were failed for _gettext_ , I am sure I did everything like it was described in the internalization guide - https://poanetwork.github.io/blockscout/#/internationalization?id=internationalization

Do i need to try to run the mentioned above command again before I push the update. Thank you in advance.

**Comment by vbaranov** [comment]
>Do i need to try to run the mentioned above command again before I push the update. Thank you in advance.

@YegorSan 

yes, try, please. But the important is the UI changes and the clearance of changes. *Gettext* test is secondary since we can fix it after merging, however, if you will manage to get it fixed, it would be awesome. Try to look if that command to fix *gettext* doesn't return some errors or warnings. And check your changes before pushing it to the remote repository in order to be sure that you don't make unwanted changes

**Pull request closed without merging**
