### PR TITLE
(Feature) New style for Lukso network

### LINKED ISSUE #1638: New style for Lukso network
Zeplin:
https://zpl.io/25OzjRn

lukso_3_3

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #1638  

Depends on #1704 (#1704 should be merged first).

## Motivation

* Updated main styles according to the designs on #1638 
* Added new type of "Dashboard" for the home page: it has only stats, no graph.

No new business logic added, only static / presentational elements added.

### Enhancements
* New Lukso styles.
* New dashboard styles.

### Incompatible Changes
* None that I can think of.

## Upgrading
*It's necessary to add a _NETWORK_DASHBOARD_GRAPH=disabled_ environment variable to make the new dashboard visible.

My local variables currently look like this:

```
export ETHEREUM_JSONRPC_VARIANT=ganache
export ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545
export ETHEREUM_JSONRPC_TRACE_URL=http://127.0.0.1:8545
export ETHEREUM_JSONRPC_WS_URL=ws://127.0.0.1:8545
export COIN=POA
export NETWORK=POA
export LOGO=/images/lukso_logo.png
export LOGO_FOOTER=/images/lukso_logo_footer.png
export STAKES_ACTIVE=true

export NETWORK_DASHBOARD_GRAPH=disabled
```

* Of course, the currently active theme in `_theme/_variables.scss_` is *Lukso*: `@import "lukso_variables";`.

The rest of the networks should work fine, except for the problems mentioned before.

### CODE REVIEW

**Comment by vbaranov** [comment]
@gabitoesmiapodo I suppose you didn't want to update master branch with the styles for LUKSO network. Maybe, you wanted to make a PR into `production-lukso` branch instead?

**Comment by gabitoesmiapodo** [comment]
> @gabitoesmiapodo I suppose you didn't want to update master branch with the styles for LUKSO network. Maybe, you wanted to make a PR into `production-lukso` branch instead?

Not sure about the right way to do this, really, or how you are handling this.

On the other hand, https://github.com/poanetwork/blockscout/pull/1704 is pointing to `master` too.

Now that you mention it, I'm not sure about either. Any suggestions are welcome.

**Comment by vbaranov** [comment]
@gabitoesmiapodo I've created https://github.com/poanetwork/blockscout/tree/production-posdao branch from master. Could you please recreate #1704 PR to that branch.

And the current PR, I suppose, should be to https://github.com/poanetwork/blockscout/tree/production-lukso branch.

In the `master` branch we store the common logic/views of all chains. But differences, specific to the chain are stored in the `production-...` branches.

**Comment by gabitoesmiapodo** [comment]
I see. I'm sorry, I wasn't aware of this.

I'll close these pull requests and open new ones.

**Comment by gabitoesmiapodo** [comment]
I'm closing this and creating a new PR for this issue.

**Pull request closed without merging**
