### PR TITLE
import emission reward ranges

### PR DESCRIPTION
**Pull request by ayrat555**
a part of #2493 
fixes https://github.com/poanetwork/blockscout/issues/2489
closes https://github.com/poanetwork/blockscout/issues/2080

## Changelog
- import emission reward ranges
## Upgrading
All you need to do is set `CHAIN_SPEC_PATH` env var with parity chain specification or create a similar specification with emission reward ranges and genesis account balances.

I'll abstract this logic for POA Network in the next PR

### CODE REVIEW

**Comment by ayrat555** [comment]
@vbaranov done

**Comment by ayrat555** [comment]
@vbaranov currently it only supports absolute path. I'll implement fetching from url now

**Comment by ayrat555** [comment]
@vbaranov  I added the ability to fetch from remote url

**Comment by vbaranov** [comment]
@ayrat555 `getminedblocks` is still unusable because it returns 502 Error, I suppose, because of a huge amount of blocks. We should add pagination for this query.

**Comment by ayrat555** [comment]
@vbaranov `emission_rewards` table is populated for emission ranges

**Comment by ayrat555** [comment]
@vbaranov `address_coin_balances` is populated for genesis balances

**Comment by vbaranov** [comment]
@ayrat555 

> @vbaranov `address_coin_balances` is populated for genesis balances

stg: `/address/0xebd37b256563e30c6f9289a8e2702f0852880833/coin_balances`

Screenshot 2019-08-09 at 19 27 20

The same is for every address from the genesis block. How is the date for the genesis block chosen?

**Comment by ayrat555** [comment]
@vbaranov I think that's a bug 
https://blockscout.com/poa/core/blocks/0/transactions
https://blockscout.com/eth/mainnet/blocks/0/transactions

**Comment by ayrat555** [comment]
I created an issue https://github.com/poanetwork/blockscout/issues/2546

**Comment by ayrat555** [comment]
@vbaranov will you create a separate issue?

**Comment by vbaranov** [comment]
> @vbaranov will you create a separate issue?

No. I would just suggest not to close #2493 with this PR. Because that issue is definitely clear: API endpoint doesn't work. And this PR is the 1st step to resolve that issue.

**Comment by ayrat555** [comment]
sounds good to me

**Pull request merged**
