### PR TITLE
Added fixed height for card chain blocks and card chain transactions.

### PR DESCRIPTION
**Pull request by YegorSan**
This PR is related to #2675 issue. 

## Motivation
Fixed height for  card chain blocks and card chain transactions requested.
### Enhancements

Added fixed height for card chain blocks and transactions.
Screenshot (1)

## Checklist for your PR

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so if necessary
  - [ ] If I added/changed/removed ENV var, I should update the list of env vars in https://github.com/poanetwork/blockscout/blob/master/docs/env-variables.md to reflect changes in the table here https://poanetwork.github.io/blockscout/#/env-variables?id=blockscout-env-variables. I've set `master` in the `Version` column.
  - [ ] If I add new indices into DB, I checked, that they don't redundant with PGHero or other tools

### CODE REVIEW

**Comment by YegorSan** [comment]
@vbaranov Hello Victor. I've created new loaders for block chain container: 
**Light mode:**
Screenshot (loaderlight)
**Dark mode:**
Screenshot (loaderdark)

**Added two more loaders to transactions container:**
transactionblock

Fixed issue with height (added fixed min height and auto max height). 

Please review. Thank's in advance.

**Comment by YegorSan** [comment]
@vbaranov I also have a question regarding gettext issue. Each time I pushing new commit, issue is appearing. First commit - everything is ok, but next one already coming with gettext issue. I know that fix for that issue is pretty simple, but maybe you tell me what can be a reason of such situation, and possibly I can prevent it for future. Thank you.

**Comment by vbaranov** [comment]
@YegorSan every time you adding/removing lines in the Elixir templates you need to change the number of line for the localization string in the internationalization files. This is why with every change you need to run https://poanetwork.github.io/blockscout/#/internationalization?id=internationalization. Please fix `gettext` issue. PR looks good.

**Comment by YegorSan** [comment]
@vbaranov Ok. Thank you so much for information Victor. I've just wondered if I am doing something wrong. Will fix gettext issue , and push update shortly.

**Pull request merged**
