### PR TITLE
do not try to convert nils in logs

### PR DESCRIPTION
**Pull request by ayrat555**
fixes https://github.com/poanetwork/blockscout/issues/1440

## Motivation
The issue related to https://github.com/poanetwork/blockscout/pull/1398. Logs of pending transactions can have `nil` values

## Changelog

- do not try to convert nil values in logs

### CODE REVIEW

**Comment by acravenho** [comment]
Hey Ayrat,

I received this error while testing:

```
2019-02-18T19:47:06.209 [error] Task #PID<0.3849.0> started from Indexer.Block.Realtime.Fetcher terminating
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Indexer.Address.CoinBalances.reducer/2
    (indexer) lib/indexer/address/coin_balances.ex:32: anonymous fn(%{address_hash: "0x03cb0021808442ad5efb61197966aef72a1def96", block_number: nil, data: "0x0000000000000000000000000000000000000000000000000de0b6b3a7640000", first_topic: "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef", fourth_topic: nil, index: nil, second_topic: "0x000000000000000000000000c4b12756474e4eed569aed9f74735310689955b9", third_topic: "0x000000000000000000000000ae9b8e05c22bae74d1e8db82c4af122b18050bd4", transaction_hash: nil, type: "pending"}) in Indexer.Address.CoinBalances.reducer/2
    (elixir) lib/enum.ex:1244: anonymous fn/4 in Enum.into/3
    (elixir) lib/enum.ex:1925: Enum."-into/4-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1925: Enum.into/4
    (stdlib) maps.erl:257: :maps.fold_1/3
    (indexer) lib/indexer/block/fetcher.ex:129: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:264: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3
    (indexer) lib/indexer/logger.ex:14: Indexer.Logger.metadata/2
    (indexer) lib/indexer/block/realtime/fetcher.ex:247: Indexer.Block.Realtime.Fetcher.fetch_and_import_block/4
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3
    Args: [7238203, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: "", method_to_url: [eth_getBalance: "", trace_block: "", trace_replayTransaction: ""], http_options: [recv_timeout: 60000, timeout: 60000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Parity], receipts_batch_size: 250, receipts_concurrency: 10}, false]
```

**Comment by ayrat555** [comment]
I couldn't reproduce the issue today. I think the problem is happening in the realtime fetcher when we're importing the latest block that wasn't mined yet. Maybe polling or subscription return it

**Comment by acravenho** [comment]
Let me run again to make sure I'm still receiving this error. I let the indexer run for a while and noticed this error 6-7 times. I'll provide more info during testing.

**Comment by ayrat555** [comment]
Thank you. Can you please log received blocks from polling and subscriptions. Maybe some of them don't have `block_hash`

**Comment by acravenho** [comment]
I was not able to replicate the exact issue either. A lot of the errors I was receiving involved around DB Connection issues for Mainnet.  I successfully indexed `core` without issue.

**Pull request merged**
