### PR TITLE
(Feature) New theming capabilites

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
## Motivation

- It's needed to add / modify the general "base" styles and layout for being able to implement the changes requested for #1476 #1638 #1664 #1672 #1726 etc.

### Enhancements

- New theming capabilites.

### Incompatible Changes

- Some navbar logos might not visible, or show wrong: default background is white, and white or white-ish logos will look bad.

## Upgrading

- Some logos will have to be changed when updating the instance(s) to this version.
- Same might happen with footer's logo.

## Extra notes

- I intended for only to introduce the needed changes for all of the upcoming themes and visual features. These are general changes, for which I tried to have some sensible defaults in case there's still not a dedicated design. Some color combinations might not look perfect, but that should be addressed later.

- I used this https://github.com/poanetwork/blockscout/issues/1664#issuecomment-484004729 and  https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens/348397311 as a base design for all of the existing sections and components *(not the actual colors, but layout, icons, etc.)*.

- @pashagonchar pointed out that the right and definitive version for the home page is this one: https://user-images.githubusercontent.com/16716926/56275944-567b5000-610a-11e9-9f12-3dc4b05682a7.png _(Lukso will have a different version, though)_.

- The new network selection component (present here https://user-images.githubusercontent.com/16716926/56275943-567b5000-610a-11e9-8b15-6f2c18376bb6.png) is not currently implemented. It's beyond the scope of this pull request (which is big enough as it is), and I will implement it on a new issue before addressing the issues for ETC and / or RSK.

- This is my current configuration:

```
export ETHEREUM_JSONRPC_VARIANT=ganache
export ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545
export ETHEREUM_JSONRPC_TRACE_URL=http://127.0.0.1:8545
export ETHEREUM_JSONRPC_WS_URL=ws://127.0.0.1:8545
export COIN=POA
export NETWORK=POA
export LOGO=/images/posdao_logo.png
export LOGO_FOOTER=/images/posdao_logo_footer.png
```

- If having trouble updating the theme or CSS files, check that your browser's cache is disabled, and please have a look at this https://github.com/poanetwork/blockscout/pull/1758#issuecomment-483751426 and this https://github.com/poanetwork/blockscout/issues/1476#issuecomment-468240899

- Current `neutral_variables` home page should look like this (don't mind the logo):

Screen Shot 2019-04-22 at 16 13 48
Screen Shot 2019-04-22 at 16 13 57
Screen Shot 2019-04-22 at 16 14 07

## Checklist for your PR

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [x] I checked whether I should update the docs and did so if necessary

### CODE REVIEW

**Comment by saneery** [comment]
@gabitoesmiapodo could you tell how to enable "Stakes" section?

**Comment by pashagonchar** [comment]
@vbaranov thanks, I'll take a look and leave my comments

**Comment by gabitoesmiapodo** [comment]
@saneery 

> @gabitoesmiapodo could you tell how to enable "Stakes" section?

Sure: it was suggested / requested on https://github.com/poanetwork/blockscout/pull/1758#issuecomment-483976447 and https://github.com/poanetwork/blockscout/pull/1758#issuecomment-483978731 that general features be merged into `master` (the purpose of this pull request) and to create specific pull requests for specific features.

As it seems the "Stakes" section will be POSDAO only, it will be implemented on a new pull request which will go into `production-posdao` once this one is merged.

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

Fixed both issues, and a few more I got to see on your screenshots.

**Comment by pashagonchar** [comment]
@gabitoesmiapodo @vbaranov

**Comment by pashagonchar** [comment]
@gabitoesmiapodo Sokol's colors are green, why we choose dark blue for Sokol?

**Comment by vbaranov** [comment]
>@gabitoesmiapodo Sokol's colors are green, why we choose dark blue for Sokol?

@pashagonchar this is because I've launched with en vars for Sokol, but with the default theme, just for testing of general styles changes. We won't see colours mismatching in the production.

**Comment by pashagonchar** [comment]
> > @gabitoesmiapodo Sokol's colors are green, why we choose dark blue for Sokol?
> 
> @pashagonchar this is because I've launched with en vars for Sokol, but with the default theme, just for testing of general styles changes. We won't see colours mismatching in the production.

Ok, thanks @vbaranov

**Comment by gabitoesmiapodo** [comment]
@pashagonchar @vbaranov 

- `Logo?` -> Maybe @vbaranov hadn't it set up (I don't know). It's got to be configured for each network, so we're going to need a new one for each network's header and footer (except for the new themes you already created).

It could be done in separate issue(s), though.

- `Can we use 3 colors for icons` -> Not really, or not in a practical / generic / simple way that I can think of at least. One plain color is achievable (that's what I implemented).

- `Green dot` -> Fixed.

- `#333 color` -> Fixed.

- `Use '...' at the end of the sentence` -> OK, finally found a way to do that. Fixed.

- `Change footer color...` -> In this case it's just a generic SCSS theme file with default colors, it should be fine on new themes.

- `60 (padding)` -> Changed it.

- Screen Shot 2019-04-24 at 15 05 48

Fixed.

-  Screen Shot 2019-04-24 at 15 06 46

OK, I've replaced it by a temporary (and similar to the others in style) button / icon. We could change it again on a new issue if we need to merge this ASAP.

- Screen Shot 2019-04-24 at 15 09 54

I've changed it to the regular text color.

- Screen Shot 2019-04-24 at 15 42 40

It should look better now.

- Screen Shot 2019-04-24 at 15 52 29

Fixed.

- Screen Shot 2019-04-24 at 16 38 31

Fixed too.

-  Screen Shot 2019-04-24 at 16 39 38

Done.

**Comment by vbaranov** [comment]
@pashagonchar 

Updated screenshots

screencapture-localhost-4000-tx-0x7ed538403f5a6a08dfb62ed5d252c8b7830f7db5698405710877650fd20f930b-internal-transactions-2019-04-25-11_58_09
screencapture-localhost-4000-blocks-8350089-transactions-2019-04-25-11_55_27
screencapture-localhost-4000-2019-04-25-11_52_25
Screenshot 2019-04-25 at 11 57 57
Screenshot 2019-04-25 at 11 55 05

**Comment by pashagonchar** [comment]
@gabitoesmiapodo 

image
make same margin between blocks

image

change color for Call to green

image

https://zpl.io/agQWXQ0

**Comment by gabitoesmiapodo** [comment]
@pashagonchar 

They should be fixed now.

**Comment by vbaranov** [comment]
@pashagonchar please let know when you will be able update layouts: there are some updates including new view of pagination in tx/address list pages. Or we could do it in a separate PR?

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

This PR is blocking a quite a few issues, maybe we can do that in a new issue if it's not super important.

**Comment by vbaranov** [comment]
@gabitoesmiapodo 
ok, I will merge this version. Meanwhile, we will not be able to release a new version of BS until all styles updates will not fit the latest layout. This is why I ask you @pashagonchar to ping us when the final layout will be ready.

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

Sure, I can implement those changes as a top priority when needed.

**Pull request merged**
