### PR TITLE
Verification links to other explorers

### PR DESCRIPTION
**Pull request by vbaranov**
**Note:** It should be merged/installed only to ETH Mainnet branch/instance
## Motivation

Add verification links to other blockchain explorers for tx details page and address details page

Screenshot 2019-05-05 at 14 10 12
Screenshot 2019-05-05 at 14 10 29

### Enhancements
- `_verify_other_explorers.html.eex` template has been added
- this template has been added to tx detail page and to address details page. It should be shown only in case of contract.
- icons for supported explorers and link icon have been added
- `image-2x` sass mixin has been added to support Retina displays

## Checklist for your PR

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [ ] I checked whether I should update the docs and did so if necessary

### CODE REVIEW

**Comment by ayrat555** [comment]
what is the purpose of this?

**Comment by igorbarinov** [comment]
The purpose it to get links to BlockScout from other explorers .
It brings traffic to all parties and increase decentralization of data.

**Comment by acravenho** [comment]
@vbaranov Don't you think the verification links push the important data out of view on the address page? I use BlockScout on a daily basis and will find this a bad user experience. 

I understand the importance of the links but they should be moved to a modal or moved to a simple button next to the QR code button. This section of the address page is also the most important real estate on a webpage which is directing people away from our content.

**Comment by pashagonchar** [comment]
@acravenho @vbaranov 
Some drafts:

1. Modal window with QR

image

2. Block under balance 

image


3. Button for verify and modal window

image

image

4. Part of the main block in the bottom 

image

**Comment by acravenho** [comment]
@pashagonchar Great work on the new designs. 

As Igor mentioned above, we should have Etherscan as the first explorer when a design is decided upon.

🤔 I personally like the QR code modal placement but that might be too hidden. If others think this is too hidden we could take a look at #4. If #4 is decided upon, maybe we could see a full-screen mockup 👍

**Comment by vbaranov** [comment]
As for me,

`#1` mixes QR-code and verification links, I am curious why a user will want to click the qr-code button to get the links to the other explorers
`#2` looks like has the same problem mentioned here https://github.com/poanetwork/blockscout/pull/1890#issuecomment-489631503. Especially in the mobile view, it will displace other important address/tx data
`#4` is good but it will be hard to keep this view compact if we will include more explorers there

I bet on `#3` (though `#4` is good too for <= 3 items)

**Comment by pashagonchar** [comment]
@vbaranov 

verify_with_other_explorers_6_1
verify_with_other_explorers_6_2

**Comment by vbaranov** [comment]
@pashagonchar please attach the link to mockup where I can get the icons to implement the final design. I need an icon for a three dots menu.

**Comment by pashagonchar** [comment]
@vbaranov 

https://zpl.io/VOxEYZ1

https://zpl.io/bPxN0wp

**Pull request merged**
