### PR TITLE
Dark theme fixes

### PR DESCRIPTION
**Pull request by maxgrapps**
Issue: https://github.com/poanetwork/blockscout/issues/2451

Also fixed gaps in tiles
Before:
Screen Shot 2019-07-31 at 00 36 21
After:
Screen Shot 2019-07-31 at 00 36 04

### CODE REVIEW

**Comment by maxgrapps** [comment]
@vbaranov added, thanks

**Comment by vbaranov** [comment]
@maxgrapps could you also lift changelog entry from published 2.0.2 release to Current section?

**Comment by vbaranov** [comment]
@maxgrapps please remove `mix.lock` update from your PR too. I believe this is unintentionally.

**Comment by maxgrapps** [comment]
@vbaranov I copied mix.lock code from blockscout repo and added new fix. 
Sorry, I don't understand about your new issue. Do you mean stage by stg? Can you send full link, please?

**Comment by ayrat555** [comment]
on address transactions page it looks like spinners are running too fast

**Comment by ayrat555** [comment]
img autocomplete addresses can not be seen

**Comment by ayrat555** [comment]
img
decoded data for transactions, transaction logs and address logs look like this

**Comment by ayrat555** [comment]
another issue I found but it's not related to the dark theme
https://github.com/poanetwork/blockscout/issues/2474

**Comment by pasqu4le** [comment]
Screenshot_20190731_114159
Screenshot_20190731_114237

Looks like these modal panels are not dark-themed

**Comment by maxgrapps** [comment]
@vbaranov I fixed some issues above, instead of:
1) qr dialog (I can't invert qr code image, we need to find a way to replace by white initially if dark mode on)
2) verify other explorers dialog (explorers icon should be svg, I can't invert it also)
3) issue https://github.com/poanetwork/blockscout/issues/2474 (It should be cropped by ... or wrapped to next line?)

**Comment by vbaranov** [comment]
@maxgrapps 

>1. qr dialog (I can't invert qr code image, we need to find a way to replace by white image initially if dark mode on)
>2. verify other explorers dialog (explorer icons should be svg, I can't invert it also)

Ok, let's leave it as is for now

>3. issue #2474 (It should be cropped by ... or wrapped to next line?)

I left a comment on the issue. Let's fix it in a separate PR https://github.com/poanetwork/blockscout/issues/2474#issuecomment-517242162

Two more remaining question regading this PR:
1. Screenshot 2019-08-01 at 14 13 43

2. dark mode is not applicable to `./graphiql` page at all. Is this intentional?

**Comment by vbaranov** [comment]
@maxgrapps also you can check from this page https://github.com/poanetwork/blockscout/pull/2463/files that you're still trying to update `mix.lock`. Please add a line-break at the end.

**Comment by maxgrapps** [comment]
@vbaranov 
1) Added text truncate for Token ID.
2) Contact source code - it's a temporary solution, because green, red colors looks invisible on dark-blue background, I will ask Pavel for new colors.
3) ./graphiql I don't added dark theme for it for now.
4) I added mix lock from poanetwork master branch. Can I delete it using
Screen Shot 2019-08-01 at 19 46 11
or leave it?

**Comment by maxgrapps** [comment]
@vbaranov added new styles for code area, added empty line at the end of mix.lock. Is it okay now?

**Comment by vbaranov** [comment]
@maxgrapps can we decrease the delay in right colours applying? https://www.loom.com/share/7a674a3f29c14e81b1bd491535923b45

@ayrat555 @pasqu4le please review again. It is on stg.

**Comment by maxgrapps** [comment]
@vbaranov I added new colors and removed invertion from this code area by commit https://github.com/poanetwork/blockscout/pull/2463/commits/41ddc4d2b985f87f8b0e8bf92ff8aa7dbc42303f
Is it okay now?

**Comment by vbaranov** [comment]
@maxgrapps 

>@vbaranov I added new colors and removed invertion from this code area by commit 41ddc4d
Is it okay now?

Apart from the question I asked you, it is ok from my perspective. Waiting for your answer and reviews from the team.

**Comment by maxgrapps** [comment]
> @maxgrapps
> 
> > @vbaranov I added new colors and removed invertion from this code area by commit [41ddc4d](https://github.com/poanetwork/blockscout/commit/41ddc4d2b985f87f8b0e8bf92ff8aa7dbc42303f)
> > Is it okay now?
> 
> Apart from the question I asked you, it is ok from my perspective. Waiting for your answer and reviews from the team.

From my side it's also fine. Okay, we'll be waiting for review...

**Pull request merged**
