### PR TITLE
Support Blockscout deployments which are not at root URLs

### PR DESCRIPTION
**Pull request by jimmay5469**
Resolves: #703

## Motivation

* `sokol-alpha.poaexplorer.com` -> `blockscout.com/poa/sokol` requires a couple JS changes because the app is no longer being hosted at the root

### Bug Fixes
* Account for blockscout deployments that are not at root URLs

### CODE REVIEW

**Comment by jimmay5469** [comment]
@ArseniiPetrovich I just took a look at sokol-alpha.poaexplorer.com and can confirm that this branch has been deployed there.

If you click to the sokol logo in the top left does it take you to the homepage and do other links around the site work? On the homepage do new blocks show up as you sit on the page?

The code I added functions exactly the same as Phoenix URL writing to allow javascript to recognize what page it is on and make the necessary channel connections. Before it was just assuming the root was `/` and not accounting for nested deployments like Phoenix URL writing does.

If all the links work but you are not seeing blocks come in on the homepage than I'll have to have someone help me set up the reverse proxy thing because I'm not exactly sure how to do that and it might help me further debug the issue.

Thanks for your help on this!

**Comment by jimmay5469** [comment]
Another idea @ArseniiPetrovich... I just noticed that sokol-alpha.poaexplorer.com is not fingerprinting the javascript assets so can you make sure you don't have a caching issue and that you are getting the latest javascript files.

**Comment by tmecklem** [comment]
@arthurra @katibest The h1 on the blocks page in this branch has been changed to an h2 and needs some updated styling as a result.

**Comment by jimmay5469** [comment]
@acravenho @ArseniiPetrovich would you guys mind testing this again?

**Comment by acravenho** [comment]
@jimmay5469 I noticed that the `USD` value on the account page disappears when a new transaction gets pushed to the address page. I hadn't noticed this previously and think it might have been introduced here.

**Comment by jimmay5469** [comment]
> @arthurra @katibest The h1 on the blocks page in this branch has been changed to an h2 and needs some updated styling as a result.

@arthurra is looking into this to be sure but it sounds like we may actually want to keep it as an `h1` so I just switched it back.

**Comment by jimmay5469** [comment]
> @jimmay5469 I noticed that the `USD` value on the account page disappears when a new transaction gets pushed. I hadn't noticed this previously and think it might have been introduced here.

This should be resolved now!

**Pull request merged**
