### PR TITLE
 show all token transfers

### PR DESCRIPTION
**Pull request by ayrat555**
resolves https://github.com/poanetwork/blockscout/issues/1792
img
img1

### Motivation

- show all token transfers for the token transfer transaction
- add generic `Token Transfer` title for transactions for which we couldn't identify a type
- fix transactions like `0xbeea8c6b013cd052c8ef9e3650c86157d4e502f0fa78c6320e4366670b6b798a` which have their tokens split into multiple internal transactions

### Changelog
- show all token transfers

### CODE REVIEW

**Comment by ayrat555** [comment]
@vbaranov 
1. I'll fix that now
2. Because it has ETH value

**Comment by ayrat555** [comment]
@vbaranov I addressed your comment about spaces

**Comment by vbaranov** [comment]
@ayrat555 please attach the screenshot of the summary block after the fix.

**Comment by ayrat555** [comment]
@vbaranov done

**Pull request merged**
