### PR TITLE
Staking dapp

### PR DESCRIPTION
**Pull request by saneery**
https://github.com/poanetwork/blockscout/issues/1709

## Changes
* Add a controller and update templates for staking page
* Authorization by MetaMask
* Send transactions by MetaMask

Use the instruction here https://github.com/poanetwork/blockscout/issues/1709 to run a test setup.

You can use some test accounts from `posdao-test-setup/accounts/keystore`, the password is `testnetpoa`

* I used server-side rendering for modal windows
* I store MetaMask account in the session and compare with an account in client side
* I pass contracts' addresses and abi in the template

### CODE REVIEW

**Comment by saneery** [comment]
@vbaranov, thanks!

> I still was not able to become a candidate with this PR. After making a stake, I don't see my address in the list of pools, but my transaction was successfully included to the block. Here is my test https://www.loom.com/share/758b8aad499a4d38b5f4fe2732fc02cc. Please, record a video of how to test this PR.

Look into a list of active pool, not into validators list. There are only pools those elected as validators in the validators list. You need wait a next epoch to be elected.

> 2. Stake/withdraw windows: the same as above point_up + address is not clickable

Where the click should redirects?

> 3. Delegators counts should be clickable:

Is there design of this page?

> 1. All checkmarks are disabled. Where are the current validators?

It isn't a checkbox, it's just a mark that pool is a validator. As I know.

> 1. I don't see "Move stake" button

I suggest it's because you didn't make a stake on active pools in the current epoch

The other remarks I will take note

**Comment by vbaranov** [comment]
@saneery

>Look into a list of active pool, not into validators list. There are only pools those elected as validators in the validators list. You need wait a next epoch to be elected.

Yes, the video is incorrect a little bit. I meant pools. My address is not added to the active pools. I created another one: https://www.loom.com/share/24d2479bc5d74a609f87e0439bae02fe. Does something stop you to provide a video of how staking functionality should work? I still don't understand is this my misconfiguration, or dapp doesn't work. Moreover, I don't see a confirmation from dapp, that transaction is successful or not. I suppose that these popups are for that https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens/349758832 https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens/349758831. Do you handle the response of the transaction?

>Where the click should redirects?

I believe to the screen with the statistics of pool https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens/349758819

>Is there design of this page?

yes, https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens/369189273

>It isn't a checkbox, it's just a mark that pool is a validator. As I know.

why does it change colour on hover then?

**Comment by saneery** [comment]
@vbaranov 

> Does something stop you to provide a video of how staking functionality should work? I still don't understand is this my misconfiguration, or dapp doesn't work. 

Strange behavior with NiftyWallet. I noticed that you set the same address in mining address, but in this case, the transaction must be failed.
https://www.loom.com/share/d370ad4f0ae74a80b1fe0a39a2667680

But NiftyWallet says that the transaction is passed
https://www.loom.com/share/8ec308c4cfc4443e9bbc6365ff5bcce9

It's a success case:
https://www.loom.com/share/3ab93bf1ab9c4b939287c99fa1d19ef6

> Moreover, I don't see a confirmation from dapp, that transaction is successful or not. I suppose that these popups are for that https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens/349758832 https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens/349758831. Do you handle the response of the transaction?

I tried to handle responses, but sometimes JS callback was not called, and I didn't investigate it anymore. I will note it too.

> why does it change colour on hover then?

@varasev, should checkmarks change color on hover?
https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens/352496708

**Comment by varasev** [comment]
> Strange behavior with NiftyWallet. I noticed that you set the same address in mining address, but in this case, the transaction must be failed.
> https://www.loom.com/share/d370ad4f0ae74a80b1fe0a39a2667680

Yes, the mining address shouldn't be the same as staking: https://github.com/poanetwork/posdao-contracts/blob/6e510e1d721fc931ff65014e5c7cba626e1693a8/contracts/abstracts/ValidatorSetBase.sol#L633 (it is called by the [`StakingAuRa.addPool`](Strange behavior with NiftyWallet. I noticed that you set the same address in mining address, but in this case, the transaction must be failed.
https://www.loom.com/share/d370ad4f0ae74a80b1fe0a39a2667680)).

> should checkmarks change color on hover?

Yes, they should change color and display a tooltip as it shown on https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens/352496708

The checkmarks should only be displayed for those addresses which are validators.

**Comment by varasev** [comment]
The issue https://github.com/poanetwork/blockscout/issues/2188 is related to this PR (some of the bugs found here are also in that issue).

**Comment by varasev** [comment]
> I don't see "Move stake" button
> I suggest it's because you didn't make a stake on active pools in the current epoch

The `Move stake` and `Withdraw` buttons shouldn't be visible if [`StakingAuRa.maxWithdrawAllowed`](https://github.com/poanetwork/posdao-contracts/blob/6e510e1d721fc931ff65014e5c7cba626e1693a8/contracts/abstracts/StakingBase.sol#L459) getter returns `0` at the moment. This can happen, for example, if [`StakingAuRa.areStakeAndWithdrawAllowed`](https://github.com/poanetwork/posdao-contracts/blob/6e510e1d721fc931ff65014e5c7cba626e1693a8/contracts/StakingAuRa.sol#L92) returns `false` (during the first blocks of a staking epoch or at the end of staking epoch).

> I tried to handle responses, but sometimes JS callback was not called, and I didn't investigate it anymore. I will note it too.

If you use `Web3`'s version greater than `1.0.0-beta.37`, you should explicitly set `web3.eth.transactionConfirmationBlocks` option (like [here](https://github.com/poanetwork/posdao-test-setup/commit/79b9ad410d195ffb131186be8e01547eb58aa7ba)).

**Pull request closed without merging**
