### PR TITLE
eth theme and eth logo

### PR DESCRIPTION
**Pull request by maxgrapps**
We need to update just _ethereum_variables.scss and ethereum_logo.svg

screencapture-localhost-4000-2019-05-03-16_03_59

### CODE REVIEW

**Comment by vbaranov** [comment]
@maxgrapps please update [CHANGELOG](https://github.com/poanetwork/blockscout/blob/master/CHANGELOG.md)

And please attach to PR the screenshot of the main page of BlockScout

**Comment by vbaranov** [comment]
@maxgrapps I've tried to build from this PR by preliminarily setting

```
@import "ethereum_variables";
@import "theme/base_variables";
```

in 

https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/assets/css/theme/_variables.scss

I've got
```
    ERROR in ./css/app.scss
    Module build failed (from ./node_modules/css-loader/index.js):
    ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

      margin-right: $common-container-margin;
                   ^
          Undefined variable: "$common-container-margin".
          in /Users/viktor/Documents/POANetwork/blockscout-max/apps/block_scout_web/assets/css/_helpers.scss (line 18, column 17)
        at runLoaders (/Users/viktor/Documents/POANetwork/blockscout-max/apps/block_scout_web/assets/node_modules/webpack/lib/NormalModule.js:303:20)
        at /Users/viktor/Documents/POANetwork/blockscout-max/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:364:11
        at /Users/viktor/Documents/POANetwork/blockscout-max/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:230:18
        at context.callback (/Users/viktor/Documents/POANetwork/blockscout-max/apps/block_scout_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
        at Object.asyncSassJobQueue.push [as callback] (/Users/viktor/Documents/POANetwork/blockscout-max/apps/block_scout_web/assets/node_modules/sass-loader/lib/loader.js:67:13)
        at Object.done [as callback] (/Users/viktor/Documents/POANetwork/blockscout-max/apps/block_scout_web/assets/node_modules/neo-async/async.js:7974:18)
        at options.error (/Users/viktor/Documents/POANetwork/blockscout-max/apps/block_scout_web/assets/node_modules/node-sass/lib/index.js:294:32)
     @ ./css/app.scss

    ERROR in ./css/app.scss (./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js??ref--5-4!./css/app.scss)
    Module build failed (from ./node_modules/sass-loader/lib/loader.js):

      margin-right: $common-container-margin;
                   ^
          Undefined variable: "$common-container-margin".
          in /Users/viktor/Documents/POANetwork/blockscout-max/apps/block_scout_web/assets/css/_helpers.scss (line 18, column 17)
     @ ./css/app.scss 2:14-169
    Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/postcss-loader/lib/index.js!node_modules/sass-loader/lib/loader.js??ref--5-4!css/app.scss:
        [0] ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js??ref--5-4!./css/app.scss 335 bytes {0} [built] [failed] [1 error]

        ERROR in ./css/app.scss (./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js??ref--5-4!./css/app.scss)
        Module build failed (from ./node_modules/sass-loader/lib/loader.js):

          margin-right: $common-container-margin;
                       ^
              Undefined variable: "$common-container-margin".
              in /Users/viktor/Documents/POANetwork/blockscout-max/apps/block_scout_web/assets/css/_helpers.scss (line 18, column 17)
```

Please provide instruction in the description of PR which changes should be made to run Blockscout with this update.

**Comment by maxgrapps** [comment]
@vbaranov 
1) About change log. I need just click edit and add something like this "#1874 - add ethereum theme" in the end?

2) How I can attach screenshot?

3) About instruction - okay, I will.

**Comment by vbaranov** [comment]
@maxgrapps 

> 1. About change log. I need just click edit and add something like this "#1874 - add ethereum theme" in the end?

yes, you can see example of this in the current open/closed PRs to the repo, for example https://github.com/poanetwork/blockscout/pull/1875/files

> 2. How I can attach screenshot?

The easiest way to drag & drop the screenshot when posting a comment

**Comment by maxgrapps** [comment]
screenshot

**Comment by maxgrapps** [comment]
@vbaranov - I attached screenshot
- We need to update only theme scss and logo file to avoid conflicts, as example for this commit it should be ethereum_variables.scss and ethereum_logo.svg

**Comment by maxgrapps** [comment]
@vbaranov I also added changes to changelog.

**Comment by maxgrapps** [comment]
@vbaranov 
1) I added new real screenshot for main page
2) Added changes to changelog
3) Try to launch my branch and it works without error

**Comment by vbaranov** [comment]
@maxgrapps works fine now.

**Pull request merged**
