### PR TITLE
Fixed modal dialog width for 'verify other explorers'

### PR DESCRIPTION
**Pull request by maxgrapps**
We need to update just _verify_other_explorers.scss

screencapture-localhost-4000-tx-0x46810b21a5ee51b6ba213097d88a4f81f8f220d73f3435142b8698582947237c-internal-transactions-2019-05-28-14_48_45

### CODE REVIEW

**Comment by maxgrapps** [comment]
@vbaranov Fixed gettext issue, thanks

**Comment by maxgrapps** [comment]
@vbaranov Seems it's okay now

**Comment by vbaranov** [comment]
@maxgrapps gettext still failed. Did you follow https://forum.poa.network/t/faq-fixing-gettext-error-in-blockscout/2444 ?

**Comment by maxgrapps** [comment]
@vbaranov runed

**Comment by vbaranov** [comment]
@maxgrapps `gettext` is broken again. How did you run it? You've run it not from the application folder but from the root folder of the app. Please read the guide once more.

**Comment by maxgrapps** [comment]
@maxgrapps yes, the problem was is in wrong path, thx

**Pull request merged**
