### PR TITLE
(Feature) New network selector

### LINKED ISSUE #2038: (Feature) New Network Selector
A new type of network selector is needed to implement the new designs found on https://github.com/poanetwork/blockscout/issues/1664 https://github.com/poanetwork/blockscout/issues/1672 etc.

image

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #2038

## Motivation

There's a new design which includes new functionality for the network selection component.

Zeplin design can be found at https://zpl.io/a7WEMEq

Besides the already functioning network selection, this implementation only implements the static elements. Extra logic should be added to make this fully work.

Correct colors should be configured later for each particular theme.

## Some screenshots

Screen Shot 2019-05-28 at 14 09 44
Screen Shot 2019-05-28 at 14 09 51
Screen Shot 2019-05-28 at 14 09 57
Screen Shot 2019-05-28 at 14 10 15
Screen Shot 2019-05-28 at 14 10 45

### Enhancements

- New network selection component.

## Checklist for your PR

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [x] I checked whether I should update the docs and did so if necessary

### CODE REVIEW

**Comment by vbaranov** [comment]
@gabitoesmiapodo could you please resolve merging conflicts?

**Comment by gabitoesmiapodo** [comment]
@vbaranov Sure, done.

**Comment by vbaranov** [comment]
@maxgrapps here are the bugs I found:

1. Stars should be coloured on the `Favourites` tab
Screenshot 2019-06-21 at 22 22 29

2. Seems, it is a consequence of the 1st issue. If to click to the star on the `Favourites` tab, the doubled row appears

3. Sokol testnet is selected, but I am on Mainnet. Nothing should be selected.

Screenshot 2019-06-21 at 22 23 01

**Comment by vbaranov** [comment]
@maxgrapps in order to increase usability could you add an ability to close the dropdown on click outside of dropdown?

**Pull request merged**
