### PR TITLE
show both eth value and token transfers

### PR DESCRIPTION
**Pull request by ayrat555**
img

fixes https://github.com/poanetwork/blockscout/issues/2522

## Changelog
- show both eth value and token transfers

### CODE REVIEW

**Comment by ayrat555** [comment]
@vbaranov fixed. I forgor `=` symbol for `eex`

**Comment by ayrat555** [comment]
@vbaranov done

**Comment by vbaranov** [comment]
@ayrat555 gettext test should be fixed. Could you do that?

**Comment by ayrat555** [comment]
@vbaranov done

**Pull request merged**
