### PR TITLE
consider `creates` param when fetching transactions

### PR DESCRIPTION
**Pull request by ayrat555**
## Changelog

-  consider `creates` param when fetching transactions

### CODE REVIEW

**Comment by goodsoft** [comment]
Do I understand correctly, that `creates` field is only provided by Parity?
Can't see this field in Geth RPC reference.

**Comment by ayrat555** [comment]
@goodsoft it looks like so

**Comment by goodsoft** [comment]
So what do we do for Geth then?

**Comment by ayrat555** [comment]
@goodsoft nothing. this field is only fetched for parity. Because sometimes parity receipts are inconsistent for new blocks.

**Pull request merged**
