### PR TITLE
feat: set a websocket keepalive from config

### LINKED ISSUE #1738: Websocket for newHeads, need to keep the connection alive
Need help to create a method to keep the socket for `netHeads` alive, in my case the socket for the `newHeads` after open needs to ping the node at a certain time for instance each `600 seconds` or the node will close de connection by not receive any `ping`. It's not a bug is just a question what is the best way to implement that feature. Thanks

### PR DESCRIPTION
**Pull request by zachdaniel**
Resolves #1738

## Motivation

* We want to set up a keepalive on websockets, because some servers will close the socket connection after receiving no messages after a period of time.

### Enhancements
* Add a keepalive argument to the websocket server.

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [x] I checked whether I should update the docs and did so if necessary

Doesn't really make sense to test a feature of a 3rd party library (in this context), so I don't think its necessary for me to add a test asserting the ping message is sent.

### CODE REVIEW

**Comment by zachdaniel** [comment]
@goodsoft yeah that’s a good idea :+1:

**Comment by zachdaniel** [comment]
@goodsoft I would like to do that, but the behavior for the websocket code explicitly defines a callback where the arguments is a list and the first element is a string containing the URL, and changing the contract there at this point would be overkill.

**Comment by goodsoft** [comment]
Sad. Okay.

**Comment by eduardonunesp** [comment]
thanks @zachdaniel for your effort to improve the websocket handling :)

**Pull request merged**
