### PR TITLE
Add functionality to try Eth RPC methods in documentation

### PR DESCRIPTION
**Pull request by saneery**
https://github.com/poanetwork/blockscout/issues/2365

We need to give users an ability to call `Eth RPC` methods from the documentation as in `RPC` documentation.

image

### CODE REVIEW

**Comment by saneery** [comment]
@vbaranov I've updated PR, could you check again, please?

**Comment by vbaranov** [comment]
@pashagonchar this is the screenshot of updated `./eth_rpc_api_docs` page. Please review it. Does it look good from your perspective?

screencapture-localhost-4000-eth-rpc-api-docs-2019-07-31-14_26_20

**Comment by saneery** [comment]
> Quantity field is still marked as invalid even if a default latest value is set.

@vbaranov fixed

**Comment by pashagonchar** [comment]
1. Use same size and style (rounded corners) for
image

like

image

2. Hover for input 
image

Just use 1 px border and blue color (for ETH theme)

3. Button width is to big
image

Please make same padding like
image

4. Remove blue border on the button
image

5. Make style for 
image

like 

image

6. Make clickable object
image

when you click on just copy to the buffer

**Comment by saneery** [comment]
@pashagonchar I've updated the PR, could you look at this?

**Comment by vbaranov** [comment]
@pashagonchar please take a look. This update is on stg server.

**Comment by pashagonchar** [comment]
1. Green corner
image

2. Blue border when click
image

3. Big padding between buttons, "clear" button need to make smaller width 
image
 
4. Input have gray border after blue, we need just 1 blue
image

5. Use full width for this object 
image
image

**Pull request merged**
