### PR TITLE
(Feature) Add new styles and "Stakes" page  for POSDAO network

### LINKED ISSUE #1476: Add new pages "Apps"/"Stakes" for POSDAO network
Menu icons:
https://zpl.io/bLPD5n7

Main page:
https://zpl.io/V4Ol5MX

Validators tab:
https://zpl.io/aR1Pxne

Stake modal window:
https://zpl.io/29Oyw7W

Stake more modal window:
https://zpl.io/2GyOGDd

Stake (user not signed) modal window:
https://zpl.io/2jQw7Zx

Withdraw modal window:
https://zpl.io/aNPoDQZ

Move stake modal window:
https://zpl.io/bWqLjxn
https://zpl.io/25OrpB3

Active pools tab:
https://zpl.io/bABEl18

Active pools tab, user not signed:
https://zpl.io/bWqLX3M

Inactive pools tab:
https://zpl.io/V4Ol5pz

-------------------------------------------------
You can leave your comment here: https://invis.io/YPQNPDTW4ZB

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #1476 

## Motivation

* Updated main styles according to the designs on #1476 (header, footer, blocks, dashboard, etc.)
* Added _Stakes_ section, currently for *POSDAO* network only (that can be changed through environment variables). 

This is all static / presentational code, so it needs all the business logic implemented as stipulated on https://github.com/poanetwork/blockscout/issues/1476#issuecomment-467610403

I intended for this new section to have all the necessary components available. I'll indicate how to get to each one in a comment below.

### Enhancements
* New general styles.
* New "Stakes" section for *POSDAO* network.

### Incompatible Changes
* Header and footer logos.

## Upgrading
* A new footer logo image is needed.
* Header and footer logos might need to be changed in all the running instances when upgrading to this version. Header background is now white, so there may be color clashing with white or light colored logos.
*It's necessary to add a _STAKES_ACTIVE_ environment variable to make the menu item visible.

My local variables currently look like this (notice the new _LOGO_FOOTER_ and _STAKES_ACTIVE_ vars):

```
export ETHEREUM_JSONRPC_VARIANT=ganache
export ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545
export ETHEREUM_JSONRPC_TRACE_URL=http://127.0.0.1:8545
export ETHEREUM_JSONRPC_WS_URL=ws://127.0.0.1:8545
export COIN=POA
export NETWORK=POA
export LOGO=/images/posdao_logo.svg
export LOGO_FOOTER=/images/posdao_logo_footer.svg
export STAKES_ACTIVE=true
```

* Of course, the currently active theme in _theme/_variables.scss_ is *POSDAO*: `@import "posdao_variables";` (not sure about how this should be by default).

The rest of the networks should work fine, except for the problems mentioned before.

### CODE REVIEW

**Comment by gabitoesmiapodo** [comment]
*All components and styles should be available at:*

* General styles update can be seen on the main page.
* The new _Stakes_ section can be accessed (if available) using the "Stakes" dropdown on the header.
* _Validators_ should show: 

"Login with Metamask" 
"Empty content" component 
Clicking the "Become Candidate" button shows related modal 
Clicking the "Remove my pool" button shows warning modal

* _Active Pools_ should show: 

Active pools list, including banned items
Account address above
Clicking the copy button shows success modal
Clicking the "Move Stakes" button shows error modal
Clicking the "Withdraw" button shows related modal 
Clicking the "Stake" button shows related modal 
Clicking the validator link button shows related modal 

* _Inactive Pools_ shows an extra checkbox besides the title.

----

I think I didn't forget anything, but there where many changes and additions... ask anything you need please.

**Comment by gabitoesmiapodo** [comment]
@saneery 

Yeah, I noticed that, and forgot to ask: Is there any standard for this project? It seems there's no `.editorconfig` or something similar to enforce this.

I could add the `.editorconfig` or please tell me if there's some linting or formatting tool I overlooked.

**Comment by saneery** [comment]
As far as I know, we don't have any linting tool for styles.

**Comment by gabitoesmiapodo** [comment]
@saneery 

All right, is 2 tab spaces on all .scss files OK?

**Comment by saneery** [comment]
> All right, is 2 tab spaces on all .scss files OK?
I think, 2 is suitable

**Comment by gabitoesmiapodo** [comment]
@saneery 

It should be better now.

**Comment by ayrat555** [comment]
Also, the build fails because there are compilation warnings

**Comment by gabitoesmiapodo** [comment]
@ayrat555 

- Added changes to CHANGELOG.
- Addressed warnings.

**Comment by gabitoesmiapodo** [comment]
Hi again @ayrat555 and @saneery 

Can this be merged? I'll do it, no problem, but I'd like to be sure.

Let me know if it needs further review, or somebody else will do it.

**Comment by ayrat555** [comment]
@gabitoesmiapodo  you `mix format` in project root to format code.

Also,`eslint` check and `gettext` are failing

**Comment by gabitoesmiapodo** [comment]
@ayrat555 

Fixed format, linting, and translations' issues.

Not sure about what the new error is (or if I would be able to fix it), though: ```ci/circleci: test_geth_http_websocket — Your tests failed on CircleCI```

**Comment by gabitoesmiapodo** [comment]
@ayrat555 @saneery 

I can't get this to pass all needed tests, and I don't know if I can do something about it.

I'd be grateful with any help you can provide with this.

**Comment by gabitoesmiapodo** [comment]
I'm closing this and creating a new PR for this issue.

**Pull request closed without merging**
