### PR TITLE
(Feature) Add styles for POSDAO Network

### LINKED ISSUE #1476: Add new pages "Apps"/"Stakes" for POSDAO network
Menu icons:
https://zpl.io/bLPD5n7

Main page:
https://zpl.io/V4Ol5MX

Validators tab:
https://zpl.io/aR1Pxne

Stake modal window:
https://zpl.io/29Oyw7W

Stake more modal window:
https://zpl.io/2GyOGDd

Stake (user not signed) modal window:
https://zpl.io/2jQw7Zx

Withdraw modal window:
https://zpl.io/aNPoDQZ

Move stake modal window:
https://zpl.io/bWqLjxn
https://zpl.io/25OrpB3

Active pools tab:
https://zpl.io/bABEl18

Active pools tab, user not signed:
https://zpl.io/bWqLX3M

Inactive pools tab:
https://zpl.io/V4Ol5pz

-------------------------------------------------
You can leave your comment here: https://invis.io/YPQNPDTW4ZB

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #1476 

As suggested here https://github.com/poanetwork/blockscout/pull/1755#issuecomment-483299313 I'm closing the original pull request and creating a new one pointing to `/production-posdao`

No changes introduced besides the new merge target.

Original PR: https://github.com/poanetwork/blockscout/pull/1704

----

## Motivation

* Updated main styles according to the designs on #1476 (header, footer, blocks, dashboard, etc.)
* Added _Stakes_ section, currently for *POSDAO* network only (that can be changed through environment variables). 

This is all static / presentational code, so it needs all the business logic implemented as stipulated on https://github.com/poanetwork/blockscout/issues/1476#issuecomment-467610403

I intended for this new section to have all the necessary components available. I'll indicate how to get to each one in a comment below.

### Enhancements
* New general styles.
* New "Stakes" section for *POSDAO* network.

### Incompatible Changes
* Header and footer logos.

## Upgrading
* A new footer logo image is needed.
* Header and footer logos might need to be changed in all the running instances when upgrading to this version. Header background is now white, so there may be color clashing with white or light colored logos.
*It's necessary to add a _STAKES_ACTIVE_ environment variable to make the menu item visible.

My local variables currently look like this (notice the new _LOGO_FOOTER_ and _STAKES_ACTIVE_ vars):

```
export ETHEREUM_JSONRPC_VARIANT=ganache
export ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545
export ETHEREUM_JSONRPC_TRACE_URL=http://127.0.0.1:8545
export ETHEREUM_JSONRPC_WS_URL=ws://127.0.0.1:8545
export COIN=POA
export NETWORK=POA
export LOGO=/images/posdao_logo.svg
export LOGO_FOOTER=/images/posdao_logo_footer.svg
export STAKES_ACTIVE=true
```

* Of course, the currently active theme in _theme/_variables.scss_ is *POSDAO*: `@import "posdao_variables";` (not sure about how this should be by default).

The rest of the networks should work fine, except for the problems mentioned before.

### CODE REVIEW

**Comment by saneery** [comment]
@vbaranov, can we update `production-posdao` branch from `master`?

**Comment by vbaranov** [comment]
@gabitoesmiapodo could you attach the screenshots of the pages with implemented styles for POSDAO chain?

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

Sorry, this part of the original PR got lost:

**All components and styles should be available at:**

* General styles update can be seen on the main page.
* The new _Stakes_ section can be accessed (if available) using the "Stakes" dropdown on the header.
* _Validators_ should show: 

"Login with Metamask" 
"Empty content" component 
Clicking the "Become Candidate" button shows related modal 
Clicking the "Remove my pool" button shows warning modal

* _Active Pools_ should show: 

Active pools list, including banned items
Account address above
Clicking the copy button shows success modal
Clicking the "Move Stakes" button shows error modal
Clicking the "Withdraw" button shows related modal 
Clicking the "Stake" button shows related modal 
Clicking the validator link button shows related modal 

* _Inactive Pools_ shows an extra checkbox besides the title.

----

**Comment by vbaranov** [comment]
@gabitoesmiapodo 

This is what I see with started `ganache` and the set of vars you provided from this PR:

screencapture-localhost-4000-2019-04-16-19_04_30

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

Hmmm, I seem to remember that something like that happened to me at first (see https://github.com/poanetwork/blockscout/issues/1476#issuecomment-468240899)

I had to stop the server, and then proceeded to delete `app.css` from `blockscout/apps/block_scout_web/priv/static/css` IIRC. There were several .css files there, I deleted them all.

The same happened later when I modified some JS code, and had to delete the files in `blockscout/apps/block_scout_web/priv/static/js` to see the changes.

I then restarted the server, .css and .js files were created again, and things started to look OK.

**Comment by gabitoesmiapodo** [comment]
@pashagonchar asked me to change POSDAO Network's logo to:

Screen Shot 2019-04-16 at 15 09 23

It's necessary to change the environment variables to:

```
export LOGO=/images/posdao_logo.png
export LOGO_FOOTER=/images/posdao_logo_footer.png
```

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

Sorry if I'm being a little obtuse here, but I got to ask: some of the changes introduced here (and on #1638, #1672, and #1726) are general changes, not only for this particular network.

Will these changes be merged into master later?

You see, I have changes here which I needed for Lukso network, and some stuff from there will be used for RSK, etc.

**Comment by vbaranov** [comment]
@gabitoesmiapodo could we divide this into two separate PRs: 
1. all we need for POSDAO into the `production-posdao` branch
2. common changes related to all chains to `master` branch

@ayrat555 what do you think?

**Comment by ayrat555** [comment]
@gabitoesmiapodo @vbaranov I experienced the same issue as Viktor on the initial page loading
also, there is a problem with price and market cap
img

I agree with Viktor if the PR can be divided into multiple PRs it should be divided

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

> all we need for POSDAO into the production-posdao branch common changes related to all chains to master branch

I don't think I could do that (or I'm not sure, to tell you the truth).

For once, it's not clear to me what's what. I don't know what's going to be into master and what into POSDAO or other networks.

Style changes are general, they will be applied to all networks, so that goes to master. I think most changes belong to master now that you mention it, but I can't be sure.

Stakes section? I don't know. Does it belong to POSDAO only? It's going to be in all networks?

1. The hint in the search field is cut off. Could we show ... at the end and a tooltip with the full hint text? -> There's no room for the placeholder to be shown fully, and I don't think it will cut itself gracefully through CSS (as in `overflow: ellipsis;`), that's for regular text only AFAIK. I'll add the text hint, though.

2. I don't see total blocks as in layout -> That could be added by whoever adds that feature. I'll add it if you wish, but it'll show some static test.

3. Block style looks different -> Sorry, but that's from another design / issue / PR (Ethereum Classic) and not implemented here. Only POSDAO designs are implemented.

4. Account balance section color is wrong: -> Same as before, that's from ETH Classic's design.

5. Address actions icons have old style -> Same as before.

6. Tabs text colour is possibly wrong -> Same.

7. A wrong colour scheme for labels: -> Same.

8. The upper corners are not rounded as in layout: -> That wasn't implemented as there was no design or indication to change that (but see `Note 1` below please).

9. Looks like api_docs doesn't fit a new layout at all -> Sorry, I don't understand. I see it fitting the available room, styles remain more or less the same (there's no design). I may be looking at the wrong section, though.

10. I don't understand what you mean, I think that's according to design. If there's some logic missing, it should be added later.

*Notes:*

1. Items `2, 3, 4, 5, 6, 7, 8` are adressed here https://github.com/poanetwork/blockscout/pull/1759, as there were new designs for all of those elements in that particular issue / PR.

I'll need your advise about how to proceed here: I could join both branches into a new one, a make a new PR (again), and everything should look fine then.

Or just merge that PR after this one, and then all visual issues will be addressed.

I'd prefer the first approach, as I need most of these changes to be able to continue working on the RSK network theme, ETH Classic, etc.

@ayrat555 

- I experienced the same issue as Viktor on the initial page loading -> See fix above.
- There is a problem with price and market cap -> I'll look into it.

**Comment by vbaranov** [comment]
@gabitoesmiapodo 

I didn't get about 3 - 10. I see here the layout https://projects.invisionapp.com/share/YPQNPDTW4ZB#/screens. Take a look at it. Do you have access?

And what I mentioned in 3 - 10 doesn't fit the layout. I talk only about POSDAO. Where did you find Classic theme? We shouldn't put Classic theme in this PR.

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

It seems we're having different 'sources of truth', sadly... As always, I'm using Zeplin's designs as my guideline for working (and the original issue, indicating which sections and components to modify https://github.com/poanetwork/blockscout/issues/1476#issue-413282354)

I only modified what's indicated there, nothing else.

ETH's classic theme is also in Zeplin, and your screenshot look like it. That's what I was talking about.

Sorry, but this is a mess.

**Comment by vbaranov** [comment]
>For once, it's not clear to me what's what. I don't know what's going to be into master and what into POSDAO or other networks.

In `master` we have general settings for all networks. And in `production-...` branches we have specified for this chain settings. We issue releases from the `master` branch. And then implement updates from master branch to `production-...` branches and deploy a new instance from `production-...` branch

>Stakes section? I don't know. Does it belong to POSDAO only? It's going to be in all networks?

It only belongs to POSDAO chain

**Comment by vbaranov** [comment]
@pashagonchar could you clarify, where are the final styles: in Zeppilin or in https://invis.io/YPQNPDTW4ZB?

**Comment by pashagonchar** [comment]
> @pashagonchar could you clarify, where are the final styles: in Zeppilin or in https://invis.io/YPQNPDTW4ZB?

@vbaranov in Invision, I'll upload latest updates to zeplin

**Comment by gabitoesmiapodo** [comment]
@vbaranov @pashagonchar 

I'll close this, and I will be creating separate branches for general / master changes to be used for all upcoming and existing networks, and a new one for POSDAO network's features.

**Comment by vbaranov** [comment]
@gabitoesmiapodo thanks

**Pull request closed without merging**
