### PR TITLE
Totally? fix dark theme

### PR DESCRIPTION
**Pull request by maxgrapps**
Issue - https://github.com/poanetwork/blockscout/issues/2451 (2 issues about validators data)
Screen Shot 2019-08-07 at 22 20 30
Screen Shot 2019-08-07 at 22 20 45

### CODE REVIEW

**Comment by pashagonchar** [comment]
> @pashagonchar is this intentional that buttons in the day mode have different colours?
> 
> Screenshot 2019-08-08 at 12 50 17

Buttons will be same color

**Comment by vbaranov** [comment]
@maxgrapps 
>is this intentional that buttons in the day mode have different colours?

it is a bug (see comment above). Please fix it.

**Comment by vbaranov** [comment]
@maxgrapps 

Also regarding to dark mode I guess we should fix this alert too:

Screenshot 2019-08-08 at 17 09 08

stg: `/tx/0x33ee933dc7b0cc7545f3d1d5d5f1db263c951af6773fff7fd82fe8de2e87d777/internal_transactions`

**Comment by maxgrapps** [comment]
@vbaranov fixed alert background and address button color for default theme
Screen Shot 2019-08-08 at 20 12 24
Screen Shot 2019-08-08 at 20 02 45

**Comment by vbaranov** [comment]
@maxgrapps 

`/tx/0xf83d3fb24b53e2925a40864808d637510ea4a532decc98afb076d7f5893edcc4/logs`

Screenshot 2019-08-09 at 11 59 30

v.s. 

Screenshot 2019-08-09 at 11 58 58

There is no box for a note in the dark mode

**Comment by vbaranov** [comment]
Verify button is invisible

`/address/0xb363a3c584b1f379c79fbf09df015da5529d4dac/contract_verifications/new`

**Comment by vbaranov** [comment]
Screenshot 2019-08-09 at 12 17 35

**Comment by vbaranov** [comment]
`/address/0x61edcdf5bb737adffe5043706e7c5bb1f1a56eea/contracts`

Screenshot 2019-08-09 at 12 25 04

**Comment by vbaranov** [comment]
@maxgrapps 

What does prevent to implement dark mode for

Screenshot 2019-08-09 at 12 56 26

if we did it for

Screenshot 2019-08-09 at 12 56 20

**Comment by vbaranov** [comment]
@maxgrapps could we customize a scroll for dark theme Screenshot 2019-08-09 at 13 07 12?

**Comment by maxgrapps** [comment]
@vbaranov added  new bunch of updates for buttons, alerts and 'verify other explorers' dialog

**Comment by maxgrapps** [comment]
> @maxgrapps could we customize a scroll for dark theme Screenshot 2019-08-09 at 13 07 12?

@vbaranov only way is to add custom scrollbar plugin, but does it better than common scrollbar (I mean how it works, not how it looks)

**Pull request merged**
