### PR TITLE
add pagination to addresses page

### PR DESCRIPTION
**Pull request by ayrat555**
resolves https://github.com/poanetwork/blockscout/issues/1782
fixes https://github.com/poanetwork/blockscout/issues/1781

## Changelog

-  add pagination to addresses page

### CODE REVIEW

**Comment by vbaranov** [comment]
@ayrat555 in the current design top view pagination could look like this:

Screenshot 2019-04-24 at 14 33 40

**Comment by ayrat555** [comment]
@vbaranov what do you mean by bottom buttons?
This is the master branch:
img

**Comment by vbaranov** [comment]
@ayrat555 

ok, it is the best practice to put pagination buttons in the top and to the bottom of the list. In the upcoming design update of Blockscout there are both: bottom and top set of buttons for pagination.

**Comment by ayrat555** [comment]
@vbaranov should I add to the top and to the bottom?

**Comment by vbaranov** [comment]
> @vbaranov should I add to the top and to the bottom?

yes

**Comment by ayrat555** [comment]
@vbaranov  I addressed your comments. Can you please take a look?

**Pull request merged**
