### PR TITLE
disable usd value for an empty exchange rate

### PR DESCRIPTION
**Pull request by ayrat555**
fixes https://github.com/poanetwork/blockscout/issues/1431

## Changelog

- disable usd value for an empty exchange rate

### CODE REVIEW

**Comment by vbaranov** [comment]
@ayrat555 please resolve merging conflicts

**Comment by ayrat555** [comment]
@vbaranov done

**Comment by vbaranov** [comment]
@ayrat555 Was not able to merge to master - many tests were failed. Please take a look when you will have a chance.

**Comment by ayrat555** [comment]
@vbaranov I fixed all tests

**Pull request merged**
