### PR TITLE
docker: fix dockerFile for secp256k1 building

### LINKED ISSUE #1352: secp256k1 / libsecp256k1 errors when building with Docker
*Describe your issue here.*

Building the Docker version comes up with errors, but the explorer functionality seems to be ok for now. I haven't noticed any direct issues because of these errors. I just wanted to bring up this issue in case it is affecting parts of the explorer that I am not aware of.

These errors happen when building the Blockscout Docker container:
```
make[1]: Entering directory '/opt/app/deps/libsecp256k1/c_src/secp256k1'
  CC       src/bench_verify.o
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  CCLD     bench_verify
  CC       src/bench_sign.o
  CCLD     bench_sign
  CC       src/bench_internal-bench_internal.o
  CCLD     bench_internal
  CC       src/bench_ecmult-bench_ecmult.o
  CCLD     bench_ecmult
  CC       src/tests-tests.o
  CCLD     tests
  CC       src/exhaustive_tests-tests_exhaustive.o
  CCLD     exhaustive_tests
  CC       src/bench_recover.o
  CCLD     bench_recover
make[1]: Leaving directory '/opt/app/deps/libsecp256k1/c_src/secp256k1'
cc -I/usr/lib/erlang/erts-10.0.3/include -I c_src/secp256k1 -I c_src/secp256k1/src -I c_src/secp256k1/include -I../libsecp256k1/src -fPIC -shared -o priv/libsecp256k1_nif.so c_src/libsecp256k1_nif.c c_src/secp256k1/.libs/libsecp256k1.a -lgmp
c_src/libsecp256k1_nif.c: In function 'ecdsa_sign':
c_src/libsecp256k1_nif.c:494:51: warning: passing argument 2 of 'secp256k1_ecdsa_signature_serialize_der' from incompatible pointer type [-Wincompatible-pointer-types]
  if (secp256k1_ecdsa_signature_serialize_der(ctx, &intermediatesig, &siglen, &signature) != 1) {
                                                   ^
In file included from c_src/libsecp256k1_nif.c:9:0:
c_src/secp256k1/src/secp256k1.c:261:5: note: expected 'unsigned char *' but argument is of type 'unsigned char (*)[74]'
 int secp256k1_ecdsa_signature_serialize_der(const secp256k1_context* ctx, unsigned char *output, size_t *outputlen, const secp256k1_ecdsa_signature* sig) {
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c_src/secp256k1/src/secp256k1.c:9:0,
                 from c_src/libsecp256k1_nif.c:9:
c_src/libsecp256k1_nif.c:497:64: warning: passing argument 3 of 'secp256k1_ecdsa_signature_parse_der' from incompatible pointer type [-Wincompatible-pointer-types]
     CHECK(secp256k1_ecdsa_signature_parse_der(ctx, &signature, &intermediatesig, siglen) == 1);
                                                                ^
c_src/secp256k1/src/util.h:40:39: note: in definition of macro 'EXPECT'
 #define EXPECT(x,c) __builtin_expect((x),(c))
                                       ^
c_src/libsecp256k1_nif.c:497:5: note: in expansion of macro 'CHECK'
     CHECK(secp256k1_ecdsa_signature_parse_der(ctx, &signature, &intermediatesig, siglen) == 1);
     ^~~~~
In file included from c_src/libsecp256k1_nif.c:9:0:
c_src/secp256k1/src/secp256k1.c:224:5: note: expected 'const unsigned char *' but argument is of type 'unsigned char (*)[74]'
 int secp256k1_ecdsa_signature_parse_der(const secp256k1_context* ctx, secp256k1_ecdsa_signature* sig, const unsigned char *input, size_t inputlen) {
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
make: *** [Makefile:31: priv/libsecp256k1_nif.so] Error 1
==> libsecp256k1
[warning] Mix compiler :make_bindings was supposed to return :ok | :noop | {:ok | :noop | :error, [diagnostic]} but it returned :error
```

And these logs appear in the logs right after the Docker process is finished (`docker logs -f {containerId}`):
```
2019-01-15T22:36:04.459 [warn] The on_load function for module libsecp256k1 returned:
{:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library /opt/app/_build/prod/lib/libsecp256k1/priv/libsecp256k1_nif.so: No such file or directory\''}}

2019-01-15T22:36:05.930 application=tzdata [info] tzdata release in place is from a file last modified Thu, 03 May 2018 23:55:14 GMT. Release file on server was last modified Mon, 31 Dec 2018 01:25:12 GMT.
2019-01-15T22:36:06.027 [warn] The on_load function for module libsecp256k1 returned:
{:error, {:load_failed, 'Failed to load NIF library: \'Error loading shared library /opt/app/_build/prod/lib/libsecp256k1/priv/libsecp256k1_nif.so: No such file or directory\''}}

2019-01-15T22:36:06.579 application=phoenix [info] Running BlockScoutWeb.Endpoint with Cowboy using http://0.0.0.0:4000
2019-01-15T22:36:06.579 application=phoenix [error] Could not find static manifest at "/opt/app/_build/prod/lib/block_scout_web/priv/static/cache_manifest.json". Run "mix phx.digest" after building your static files or remove the configuration from "config/prod.exs".
2019-01-15T22:36:07.079 application=tzdata [info] Tzdata has updated the release from 2018e to 2018i
```

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Operating System: Mac OSX 10.14.2 Mojave

### Steps to reproduce
1. Clone the repo
2. Follow setup instructions
3. `cd docker`
4. `make start`

### Expected behaviour

No error logs in the build process with`secp256k1` and no errors logs with `libsecp256k1_nif`.

### Actual behaviour

Error logs appear in the build process and at the very first log items after the Docker container is built.

### PR DESCRIPTION
**Pull request by rjl493456442**
Fix #1352

### CODE REVIEW

**Comment by hadv** [comment]
@rjl493456442 this fix is for `bitwalker/alpine-elixir-phoenix:latest`, not for `1.7.1`, right? because if I use `1.7.1` then still can build docker image without error

**Comment by rjl493456442** [comment]
@hadv It seems. I'll try to build with the current dockerfile. If it works I'll close it.

Thank you for reminding.

**Comment by rjl493456442** [comment]
I run the current dockerfile, still has such error:

```
make[1]: Leaving directory '/opt/app/deps/libsecp256k1/c_src/secp256k1'
cc -I/usr/lib/erlang/erts-10.0.3/include -I c_src/secp256k1 -I c_src/secp256k1/src -I c_src/secp256k1/include -I../libsecp256k1/src -fPIC -shared -o priv/libsecp256k1_nif.so c_src/libsecp256k1_nif.c c_src/secp256k1/.libs/libsecp256k1.a -lgmp
c_src/libsecp256k1_nif.c: In function 'ecdsa_sign':
c_src/libsecp256k1_nif.c:494:51: warning: passing argument 2 of 'secp256k1_ecdsa_signature_serialize_der' from incompatible pointer type [-Wincompatible-pointer-types]
  if (secp256k1_ecdsa_signature_serialize_der(ctx, &intermediatesig, &siglen, &signature) != 1) {
                                                   ^
In file included from c_src/libsecp256k1_nif.c:9:0:
c_src/secp256k1/src/secp256k1.c:261:5: note: expected 'unsigned char *' but argument is of type 'unsigned char (*)[74]'
 int secp256k1_ecdsa_signature_serialize_der(const secp256k1_context* ctx, unsigned char *output, size_t *outputlen, const secp256k1_ecdsa_signature* sig) {
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c_src/secp256k1/src/secp256k1.c:9:0,
                 from c_src/libsecp256k1_nif.c:9:
c_src/libsecp256k1_nif.c:497:64: warning: passing argument 3 of 'secp256k1_ecdsa_signature_parse_der' from incompatible pointer type [-Wincompatible-pointer-types]
     CHECK(secp256k1_ecdsa_signature_parse_der(ctx, &signature, &intermediatesig, siglen) == 1);
                                                                ^
c_src/secp256k1/src/util.h:40:39: note: in definition of macro 'EXPECT'
 #define EXPECT(x,c) __builtin_expect((x),(c))
                                       ^
c_src/libsecp256k1_nif.c:497:5: note: in expansion of macro 'CHECK'
     CHECK(secp256k1_ecdsa_signature_parse_der(ctx, &signature, &intermediatesig, siglen) == 1);
     ^~~~~
In file included from c_src/libsecp256k1_nif.c:9:0:
c_src/secp256k1/src/secp256k1.c:224:5: note: expected 'const unsigned char *' but argument is of type 'unsigned char (*)[74]'
 int secp256k1_ecdsa_signature_parse_der(const secp256k1_context* ctx, secp256k1_ecdsa_signature* sig, const unsigned char *input, size_t inputlen) {
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
make: *** [Makefile:31: priv/libsecp256k1_nif.so] Error 1
==> libsecp256k1
[warning] Mix compiler :make_bindings was supposed to return :ok | :noop | {:ok | :noop | :error, [diagnostic]} but it returned :error
```

**Comment by hadv** [comment]
@rjl493456442 ah, sorry! Actually. I use your Dockerfile on puppeth's repo some days ago and can build with `1.7.1` I didnot check the Dockerfile on this repo

**Comment by mattkanwisher** [comment]
Any reason this never got merged? We are experiencing similar issue

**Comment by rjl493456442** [comment]
@acravenho Can you merge this PR :) I think the fix really makes sense.

**Comment by acravenho** [comment]
@vbaranov can you please take a look and see if this can get merged? Thanks 👍

**Pull request merged**
