### PR TITLE
Typo issues, dropdown issues

### PR DESCRIPTION
**Pull request by maxgrapps**
1) Added underline on hover for 'download csv' button
Screen Shot 2019-06-28 at 15 51 16

2) Fixed hover for transaction links on resolution 320-992
Screen Shot 2019-06-28 at 15 52 08

3) Fixed network selector gaps in 320px-375px resolution
Before:

After:
Screen Shot 2019-06-28 at 12 47 26

4) Added new styles for tokens dropdown
Before:
Screen Shot 2019-06-28 at 15 54 10
After:
Screen Shot 2019-06-28 at 14 55 12

5) Added dashed underline for contract links instead of dashed border with gap, added straight underline on hover
After:
 - default
 - hover

6) Fixed token transfer info inside of tile for mobile resolution
Before:
was
After:
Screen Shot 2019-06-28 at 16 34 57

### CODE REVIEW

**Comment by maxgrapps** [comment]
@vbaranov I returned code from master for:

apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex
apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex

Can you please check is it correct html inside now inside?

**Comment by vbaranov** [comment]
@maxgrapps you don't need to change any `.eex` template. Please check this page with the differences you are trying to make in templates against `master` branch.

**Comment by vbaranov** [comment]
@maxgrapps I meant this page https://github.com/poanetwork/blockscout/pull/2269/files

**Comment by maxgrapps** [comment]
@vbaranov seems it's okay, now the difference is only in one string
Screen Shot 2019-07-02 at 11 45 30

**Comment by vbaranov** [comment]
@maxgrapps I still see

Screenshot 2019-07-02 at 11 55 04


And could you please get upstream from master, because there are merging conflicts

**Pull request closed without merging**
