### PR TITLE
Add configurable block transformers

### LINKED ISSUE #968: Geth Clique blocks always mined by 0x000
In order to find the miner for Geth Clique blocks, we must use `clique.getSignersAtHash('0x86837f148f096f1ce53463ecb4acf3d99bae0b2f0297dacbb6d33fcfdb7c04d9')`. 

It also appears that we may be able to extract the signer from the `extraData` field. https://github.com/ethereum/EIPs/issues/225

### PR DESCRIPTION
**Pull request by alexgaribay**
Closes #968 

## Motivation

For some chains, custom transforms for are needed to calculate expected data about a block. In Clique, a proof-of-authority chain, the miner address is the burn address for every block when requesting data. For this PoA chain, there is a signer of the block, which we can call the miner for all intents and purposes, that can be recovered from doing some transforms on a block's header.

This PR adds in support for calculating the signer for a block based on the block's header information. Additionally, blocks are run through a transformer before going through the import process. Clique in this case has its own specific transformer. The transformer can be set in the indexers configuration.

### Enhancements
* Add configurable block transformers
* Add support for generating the address of the signer for Clique

### CODE REVIEW

**Comment by acravenho** [comment]
Hey @alexgaribay,

I'm receiving the following error after compiling:

```
c_src/libsecp256k1_nif.c:497:64: warning: incompatible pointer types passing 'unsigned char (*)[74]' to parameter of type 'const unsigned char *' [-Wincompatible-pointer-types]
    CHECK(secp256k1_ecdsa_signature_parse_der(ctx, &signature, &intermediatesig, siglen) == 1);
                                                               ^~~~~~~~~~~~~~~~
c_src/secp256k1/src/util.h:53:18: note: expanded from macro 'CHECK'
    if (EXPECT(!(cond), 0)) { \
                 ^~~~
c_src/secp256k1/src/util.h:40:39: note: expanded from macro 'EXPECT'
#define EXPECT(x,c) __builtin_expect((x),(c))
                                      ^
c_src/secp256k1/src/secp256k1.c:224:124: note: passing argument to parameter 'input' here
int secp256k1_ecdsa_signature_parse_der(const secp256k1_context* ctx, secp256k1_ecdsa_signature* sig, const unsigned char *input, size_t inputlen) {
                                                                                                                           ^
2 warnings generated.
ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [priv/libsecp256k1_nif.so] Error 1
==> libsecp256k1
[warning] Mix compiler :make_bindings was supposed to return :ok | :noop | {:ok | :noop | :error, [diagnostic]} but it returned :error
Compiling 1 file (.erl)
src/libsecp256k1.erl:146: Warning: function not_loaded/1 is unused
Generated libsecp256k1 app
```

I attempted to `cd app/deps`, `make libsecp256k1`, but nothing changed.

What originally prompted me to recompile was this error:

```
08:05:20.758 [error] GenServer :block_catchup_sequencer terminating
** (UndefinedFunctionError) function :libsecp256k1.ecdsa_recover_compact/4 is undefined (module :libsecp256k1 is not available)
    (libsecp256k1) :libsecp256k1.ecdsa_recover_compact(<<219, 249, 218, 206, 221, 171, 175, 255, 95, 158, 28, 217, 255, 138, 141, 132, 158, 241, 177, 150, 173, 30, 63, 19, 208, 211, 255, 78, 22, 160, 185, 201>>, <<251, 161, 42, 107, 160, 169, 40, 168, 87, 200, 26, 195, 230, 4, 124, 118, 50, 173, 67, 49, 40, 245, 15, 199, 37, 91, 114, 111, 145, 73, 141, 148, 100, 215, 163, 180, 63, 202, 0, 250, 15, 147, 218, 191, 81, 182, 226, 17, 108, 27, ...>>, :uncompressed, 0)
    (indexer) lib/indexer/block/util.ex:67: Indexer.Block.Util.recover_pub_key/2
    (indexer) lib/indexer/block/transform/clique.ex:12: Indexer.Block.Transform.Clique.transform/1
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (indexer) lib/indexer/block/fetcher.ex:100: Indexer.Block.Fetcher.fetch_and_import_range/2
    (indexer) lib/indexer/block/catchup/fetcher.ex:168: Indexer.Block.Catchup.Fetcher.fetch_and_import_range_from_sequence/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.809.0>, {:undef, [{:libsecp256k1, :ecdsa_recover_compact, [<<219, 249, 218, 206, 221, 171, 175, 255, 95, 158, 28, 217, 255, 138, 141, 132, 158, 241, 177, 150, 173, 30, 63, 19, 208, 211, 255, 78, 22, 160, 185, 201>>, <<251, 161, 42, 107, 160, 169, 40, 168, 87, 200, 26, 195, 230, 4, 124, 118, 50, 173, 67, 49, 40, 245, 15, 199, 37, 91, 114, 111, 145, 73, 141, 148, 100, 215, 163, 180, 63, 202, 0, ...>>, :uncompressed, 0], []}, {Indexer.Block.Util, :recover_pub_key, 2, [file: 'lib/indexer/block/util.ex', line: 67]}, {Indexer.Block.Transform.Clique, :transform, 1, [file: 'lib/indexer/block/transform/clique.ex', line: 12]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1314]}, {Indexer.Block.Fetcher, :fetch_and_import_range, 2, [file: 'lib/indexer/block/fetcher.ex', line: 100]}, {Indexer.Block.Catchup.Fetcher, :fetch_and_import_range_from_sequence, 3, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 168]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
State: %Indexer.Sequence{bound_queue: %Indexer.BoundQueue{maximum_size: nil, queue: {[{7, 0}, {17, 8}, {27, 18}, {37, 28}, {47, 38}, {57, 48}, {67, 58}, {77, 68}, {87, 78}, {97, 88}, {107, 98}, {117, 108}, {127, 118}, {137, 128}, {147, 138}, {157, 148}, {167, 158}, {177, 168}, {187, 178}, {197, 188}, {207, 198}, {217, 208}, {227, 218}, {237, 228}, {247, 238}, {257, 248}, {267, 258}, {277, 268}, {287, 278}, {297, 288}, {307, 298}, {317, 308}, {327, 318}, {337, 328}, {347, 338}, {357, 348}, {367, 358}, {377, 368}, {387, 378}, {397, 388}, {407, 398}, {417, 408}, {427, 418}, {437, 428}, {447, ...}, {...}, ...], [{3261727, 3261718}, {3261717, 3261708}, {3261707, 3261698}, {3261697, 3261688}, {3261687, 3261678}, {3261677, 3261668}, {3261667, 3261658}, {3261657, 3261648}, {3261647, 3261638}, {3261637, 3261628}, {3261627, 3261618}, {3261617, 3261608}, {3261607, 3261598}, {3261597, 3261588}, {3261587, 3261578}, {3261577, 3261568}, {3261567, 3261558}, {3261557, 3261548}, {3261547, 3261538}, {3261537, 3261528}, {3261527, 3261518}, {3261517, 3261508}, {3261507, 3261498}, {3261497, 3261488}, {3261487, 3261478}, {3261477, 3261468}, {3261467, 3261458}, {3261457, 3261448}, {3261447, 3261438}, {3261437, 3261428}, {3261427, 3261418}, {3261417, 3261408}, {3261407, 3261398}, {3261397, 3261388}, {3261387, 3261378}, {3261377, 3261368}, {3261367, 3261358}, {3261357, 3261348}, {3261347, 3261338}, {3261337, 3261328}, {3261327, 3261318}, {3261317, 3261308}, {3261307, 3261298}, {3261297, ...}, {...}, ...]}, size: 326173}, current: nil, step: -10}
08:05:20.762 application=indexer [error] Catchup index stream exited with reason ({:undef, [{:libsecp256k1, :ecdsa_recover_compact, [<<219, 249, 218, 206, 221, 171, 175, 255, 95, 158, 28, 217, 255, 138, 141, 132, 158, 241, 177, 150, 173, 30, 63, 19, 208, 211, 255, 78, 22, 160, 185, 201>>, <<251, 161, 42, 107, 160, 169, 40, 168, 87, 200, 26, 195, 230, 4, 124, 118, 50, 173, 67, 49, 40, 245, 15, 199, 37, 91, 114, 111, 145, 73, 141, 148, 100, 215, 163, 180, 63, 202, 0, 250, 15, 147, ...>>, :uncompressed, 0], []}, {Indexer.Block.Util, :recover_pub_key, 2, [file: 'lib/indexer/block/util.ex', line: 67]}, {Indexer.Block.Transform.Clique, :transform, 1, [file: 'lib/indexer/block/transform/clique.ex', line: 12]}, {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1314]}, {Indexer.Block.Fetcher, :fetch_and_import_range, 2, [file: 'lib/indexer/block/fetcher.ex', line: 100]}, {Indexer.Block.Catchup.Fetcher, :fetch_and_import_range_from_sequence, 3, [file: 'lib/indexer/block/catchup/fetcher.ex', line: 168]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}, {Task.Supervised, :reply, 5, [file: 'lib/task/supervised.ex', line: 38]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}). Restarting
```

**Comment by alexgaribay** [comment]
I’m aware of the issue. I was trying to solve it for CI yesterday.

**Comment by alexgaribay** [comment]
@acravenho I got the build to complete and ensure that that library is compiled properly. I had to add `autoconf build-essential libgmp3-dev libtool` as installed packages for the build. Will this require updating the terraform scripts?

**Comment by acravenho** [comment]
> @acravenho I got the build to complete and ensure that that library is compiled properly. I had to add `autoconf build-essential libgmp3-dev libtool` as installed packages for the build. Will this require updating the terraform scripts?

@alexgaribay Some of those may already be included in Terraform but here is the file where it should be added https://github.com/poanetwork/blockscout-terraform/blob/master/modules/stack/libexec/init.sh

**Comment by acravenho** [comment]
@alexgaribay Do you think we should add anything under https://github.com/poanetwork/blockscout/tree/ag-clique-miner#requirements for the new dependencies?

**Pull request merged**
