### PR TITLE
Value-ticker gaps fix

### PR DESCRIPTION
**Pull request by maxgrapps**
Issue - https://github.com/poanetwork/blockscout/issues/2472

### CODE REVIEW

**Comment by vbaranov** [comment]
@maxgrapps 

And once more:
Screenshot 2019-08-07 at 17 39 05

`/tx/0xc73a43b82883dd3a0eef4eda479abb4e3ac6d2153cb5b7198e0a138cc312d3d4/token_transfers`

**Comment by vbaranov** [comment]
@maxgrapps 

One more:
Screenshot 2019-08-07 at 18 21 44

`/tx/0x937902fe1c048596791fb887771a242880bd919b148282edcfcb357dd5e96a68/internal_transactions`

**Comment by vbaranov** [comment]
@maxgrapps 

Screenshot 2019-08-07 at 18 23 22

`/tx/0x937902fe1c048596791fb887771a242880bd919b148282edcfcb357dd5e96a68/token_transfers`

**Comment by maxgrapps** [comment]
> @maxgrapps
> 
> Screenshot 2019-08-07 at 18 23 22
> 
> `/tx/0x937902fe1c048596791fb887771a242880bd919b148282edcfcb357dd5e96a68/token_transfers`

Added fixes for your new issues, except this one. I can't separate link from text in this h3 heading. Can you add space symbol inside this eex code output result?
Screen Shot 2019-08-07 at 19 30 20

**Comment by ayrat555** [comment]
@maxgrapps wouldn't it work `<% ... %> <% "  " %> <% ... %>`?

**Comment by vbaranov** [comment]
@maxgrapps 

One more:

Screenshot 2019-08-08 at 14 15 03
`/tokens/0x58959e0c71080434f237bd42d07cd84b74cef438/token_transfers`

**Comment by maxgrapps** [comment]
@vbaranov added fixes for 3 latest issues
Screen Shot 2019-08-08 at 20 34 24
Screen Shot 2019-08-08 at 20 33 28
Screen Shot 2019-08-08 at 20 32 51

**Comment by maxgrapps** [comment]
@vbaranov fixed wgbc token

**Comment by vbaranov** [comment]
@maxgrapps fix merging conflicts

**Pull request merged**
