### PR TITLE
Move network selection dropdown in navbar to left hand navbar.

### PR DESCRIPTION
**Pull request by svenski123**
### Bug Fixes
- Adjust placement of network dropdown box in navbar such that search box is no longer clipped on mobile devices.

### CODE REVIEW

**Comment by arthurra** [comment]
@svenski123 you could simply set the `.navbar-nav .dropdown-menu` to `position: absolute` and I think that would solve the issue that you're seeing.

**Comment by arthurra** [comment]
@svenski123 is your intention to have the search bar extend the full width of the menu?

**Comment by svenski123** [comment]
@arthurra My intention was for the search bar to be the width of the device (as per attached screenshot).
However this caused a change desktop version that was undesirable (per comments).

I since have seen that santteegt has been approved for this bounty today so I gather I should leave it to him to address - not sure what ettiquette is here; perhaps I should withdraw this pull request?

img_6945

**Comment by svenski123** [comment]
As my curiosity was piqued, I revisited this.
Commit comments should be self explanatory, the change is now smaller than before, desktop layout is now unchanged and clipped search box issue on mobile is fixed.
(At least on Mozilla Firefox and iOS Safari).

**Comment by acravenho** [comment]
Thanks, @svenski123, I'll take a look at it and also make sure that you're taken care of regarding the bounty if it gets merged.

**Comment by acravenho** [comment]
@svenski123 This issue has been resolved by #1012. Please DM me on Gitter with you Ethereum Address.

**Pull request closed without merging**
