### PR TITLE
New block loading animation

### PR DESCRIPTION
**Pull request by maxgrapps**
Screen Shot 2019-07-12 at 16 02 01

### CODE REVIEW

**Comment by maxgrapps** [comment]
@vbaranov yes, it will. I added this ability by latest commit, thanks

**Comment by vbaranov** [comment]
@maxgrapps is this intentional behaviour that block with animation is permanently on the 1st position? it never disappears

**Comment by maxgrapps** [comment]
@vbaranov temporarily, yes. But I will add fixes later for this animation, to skip this loader after 1-1.5s

**Comment by vbaranov** [comment]
@maxgrapps we cannot merge temporary solutions to master branch. Let me know when you will finish. Then I will return to review.

**Pull request closed without merging**
