### PR TITLE
525 design cleanup api doc

### PR DESCRIPTION
**Pull request by katibest**
Resolves: #525

## Motivation
Updated the visual aspects of the API docs to match the rest of the explorer app. 

## Changelog
* Updated code to match the rest of the web (tables --> Descriptor tags and columns) to have a little more flexibility. 
* Updated code inputs to our tile muted to match the other places we're doing something similar 

localhost_4000_en_api_docs 1

### CODE REVIEW

**Comment by katibest** [comment]
@acravenho  Just realized there's no Gettext on the API doc - should we be adding it in?

**Comment by acravenho** [comment]
screen shot 2018-08-17 at 7 27 46 am

@katibest The top `Server Response` blends with the bottom `Example Responses` and it's a little confusing from a user experience standpoint. Is there a way to make them stand out more or divide them better so the user can easily see the difference after trying an API endpoint? 

WDYT @sabondano

**Comment by katibest** [comment]
@acravenho you mean these two sections?
44264036-2aac7100-a1ef-11e8-8e3b-5899ee71ecca

If so we can add a little margin between them and line.

**Comment by acravenho** [comment]
@katibest Yes, that would be perfect.

**Comment by katibest** [comment]
44264036-2aac7100-a1ef-11e8-8e3b-5899ee71ecca

@acravenho  Updated with a little more space and some lines!

**Pull request merged**
