### PR TITLE
(Feature) New pages for POSDAO network 

### LINKED ISSUE #1476: Add new pages "Apps"/"Stakes" for POSDAO network
Menu icons:
https://zpl.io/bLPD5n7

Main page:
https://zpl.io/V4Ol5MX

Validators tab:
https://zpl.io/aR1Pxne

Stake modal window:
https://zpl.io/29Oyw7W

Stake more modal window:
https://zpl.io/2GyOGDd

Stake (user not signed) modal window:
https://zpl.io/2jQw7Zx

Withdraw modal window:
https://zpl.io/aNPoDQZ

Move stake modal window:
https://zpl.io/bWqLjxn
https://zpl.io/25OrpB3

Active pools tab:
https://zpl.io/bABEl18

Active pools tab, user not signed:
https://zpl.io/bWqLX3M

Inactive pools tab:
https://zpl.io/V4Ol5pz

-------------------------------------------------
You can leave your comment here: https://invis.io/YPQNPDTW4ZB

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
**Depends heavily on #1807 being reviewed / approved / merged  first.**

Closes #1476 

## Motivation

- Add the new styles required for POSDAO Network.
- Added *only* the sections and components present in https://github.com/poanetwork/blockscout/issues/1476#issue-413282354 (Zeplin links on that list).

I'm not sure about the differences present on https://invis.io/YPQNPDTW4ZB, and I would need the Zeplin files anyway.

- Local configuration is as this:

```
export ETHEREUM_JSONRPC_VARIANT=ganache
export ETHEREUM_JSONRPC_HTTP_URL=http://127.0.0.1:8545
export ETHEREUM_JSONRPC_TRACE_URL=http://127.0.0.1:8545
export ETHEREUM_JSONRPC_WS_URL=ws://127.0.0.1:8545
export COIN=POA
export NETWORK=POA
export LOGO=/images/posdao_logo.png
export LOGO_FOOTER=/images/posdao_logo_footer.png
```

- You can get to the new sections / components by doing:

* The new _Stakes_ section can be accessed using the "Stakes" dropdown on the header.
* _Validators_ should show: 

"Login with Metamask" 
"Empty content" component 
Clicking the "Become Candidate" button shows related modal 
Clicking the "Remove my pool" button shows warning modal

* _Active Pools_ should show: 

Active pools list, including banned items
Account address above
Clicking the copy button shows success modal
Clicking the "Move Stakes" button shows error modal
Clicking the "Withdraw" button shows related modal 
Clicking the "Stake" button shows related modal 
Clicking the validator link button shows related modal 

* _Inactive Pools_ shows an extra checkbox besides the title.

### Enhancements

New styles for POSDAO Network

### Incompatible Changes

I don't think so.

### CODE REVIEW

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

Are those old screenshots (I mean, previous to the `new-theming-capabilites` ->  `master` merging)?

Most or all of those issues should be fixed already.

Also, I don't understand what item number 2 means.

**Comment by vbaranov** [comment]
>Also, I don't understand what item number 2 means.

When you on the "... pools" tab it should be another header name for 1st column

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

Oh, I see now.

I'll change it, no problem, but please keep in mind that all of this is still missing all of the business logic (it's mostly presentational / static code).

Which also begs the question of who will add that logic and when will that be done (https://github.com/poanetwork/blockscout/issues/1476#issuecomment-467610403)

**Comment by gabitoesmiapodo** [comment]
@vbaranov 

- Fixed the "Pools" text issue.
- The rest should be fixed as well.

**Comment by vbaranov** [comment]
@gabitoesmiapodo tnx. I will merge the current state to not block the logic creation for embedded dapp by @saneery . @pashagonchar if there will be some corrections let's create a separate issue for Gabriel.

**Comment by gabitoesmiapodo** [comment]
@vbaranov @pashagonchar 

Sure, let me know if there's anything else you need.

**Pull request merged**
