### PR TITLE
566 testnet variables

### PR DESCRIPTION
**Pull request by katibest**
Resolves: #566

## Motivation

Created variable stylesheets of testnet with a write up for other to make their own branded version of the blockchain.

## Changelog
* Created testnet variable stylesheets
* Created a base variable stylesheets for variable that do not to be changed
* Updated logo to be easily interchangeable

## To Test

* Use our documentation below to try out creating your own block chain version 

> Hello. Welcome to creating your own forked blockchain brought to you by POA!
> 
> Step 1
> Css -> Components -> Theme
> Inside theme folder duplicate _example_variables.scss & rename
> 
> Step 2
> Change $primary color to your main branding color
> 
> Step 3
> Change $secondary - this will be tooltips and the second line in the chart
> $tertiary are all the links and secondary so it can be the same as $secondary or change it up to your liking. Please look at a color wheel or go to https://coolors.co/app if you need help!
>
> Step 4
> To make it all work go to variables.scss and change out line 2 to your file name
>
> Step 5
> Import logo image into images folder
> & change logo name in the config/config.exs file on line 14
>

### CODE REVIEW

**Comment by acravenho** [comment]
@katibest 

The variables work great. 

1. It looks like we're missing the logo file for `Rinkeby`
2. The fonts of the logos look different from the mockups
3. Can you include the logos/variable files for `Ethereum Mainnet` and `Sokol`?

**Comment by katibest** [comment]
@acravenho I added ethereum mainnet and sokol! Can you check all the logos to see if theyre acting funny on your computer. I embedded everything so they should be ok now!

**Comment by katibest** [comment]
screen shot 2018-08-21 at 4 12 17 pm

screen shot 2018-08-21 at 4 12 47 pm

**Comment by acravenho** [comment]
@katibest I'm still seeing the odd font for the logo

### I'm seeing this

screen shot 2018-08-22 at 6 40 17 am


### Mockup
screen shot 2018-08-22 at 6 41 59 am

**Comment by acravenho** [comment]
It's still not working correctly. The header height is not the same as `sokol` or `core`, the dropdown links are difficult to read, the font on the logo is still wrong. 

screen shot 2018-08-22 at 1 43 36 pm


screen shot 2018-08-22 at 1 45 42 pm


screen shot 2018-08-22 at 1 46 23 pm

**Comment by KronicDeth** [comment]
Rebased on master.

**Comment by katibest** [comment]
@acravenho  Take a look! We updated the documentation to match our changes.

**Pull request merged**
