### PR TITLE
Return gasPrice at gettxinfo API's method

### PR DESCRIPTION
**Pull request by saneery**
https://github.com/poanetwork/blockscout/issues/2348
## Motivation

Add `gasPrice` field at the result of `gettinfo` method

  - [x] I added an entry to `CHANGELOG.md` with this PR
  - [x] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.
  - [x] I checked whether I should update the docs and did so if necessary

### CODE REVIEW

**Comment by ayrat555** [comment]
Please add json schema test so we won't lose anything in the future

**Comment by saneery** [comment]
> Please add json schema test so we won't lose anything in the future

@ayrat555 what the schema? where can I find an example?

**Comment by ayrat555** [comment]
@saneery https://en.wikipedia.org/wiki/JSON#JSON_Schema

we didn't test JSON schema yet but I think it's time to start. this PR is a good opportunity https://github.com/jonasschmidt/ex_json_schema

**Comment by ayrat555** [comment]
@saneery are you going to resolve my comment? I didn't get an answer in 2 weeks

**Comment by saneery** [comment]
@ayrat555 maybe it should be different PR since we need to add a new dependency?
Maybe we should create a new issue to add JSON schema tests?

**Pull request merged**
